//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Css.Parser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Css.Parser.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized &apos;@&apos; block type..
        /// </summary>
        internal static string ParseErrorType_AtDirectiveNameMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_AtDirectiveNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a semicolon (&apos;;&apos;) to end the current @ block..
        /// </summary>
        internal static string ParseErrorType_AtDirectiveSemicolonMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_AtDirectiveSemicolonMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a close bracket (&apos;]&apos;) in the attribute selector..
        /// </summary>
        internal static string ParseErrorType_AttributeSelectorCloseBracketMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_AttributeSelectorCloseBracketMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an element name in the attribute selector..
        /// </summary>
        internal static string ParseErrorType_AttributeSelectorElementMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_AttributeSelectorElementMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a comparison operator between the name and value in the attribute selector..
        /// </summary>
        internal static string ParseErrorType_AttributeSelectorOperationMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_AttributeSelectorOperationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a value string after the operator in the attribute selector..
        /// </summary>
        internal static string ParseErrorType_AttributeSelectorValueMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_AttributeSelectorValueMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a class name after the dot (&apos;.&apos;)..
        /// </summary>
        internal static string ParseErrorType_ClassNameMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_ClassNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The closing brace doesn&apos;t match an opening brace..
        /// </summary>
        internal static string ParseErrorType_CloseBraceMismatch {
            get {
                return ResourceManager.GetString("ParseErrorType_CloseBraceMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment is unclosed, &apos;*/&apos; expected..
        /// </summary>
        internal static string ParseErrorType_CloseCommentMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_CloseCommentMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The block is unclosed, &apos;}&apos; expected..
        /// </summary>
        internal static string ParseErrorType_CloseCurlyBraceMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_CloseCurlyBraceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function arguments are unclosed, &apos;)&apos; expected..
        /// </summary>
        internal static string ParseErrorType_CloseFunctionBraceMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_CloseFunctionBraceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a closing quote for the string value..
        /// </summary>
        internal static string ParseErrorType_CloseQuoteMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_CloseQuoteMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a colon (&apos;:&apos;) between the property and value in the &quot;(property) : (value)&quot; declaration..
        /// </summary>
        internal static string ParseErrorType_ColonMissingInDeclaration {
            get {
                return ResourceManager.GetString("ParseErrorType_ColonMissingInDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a custom property name (prefixed with &apos;--&apos;)..
        /// </summary>
        internal static string ParseErrorType_CustomPropertyNameExpected {
            get {
                return ResourceManager.GetString("ParseErrorType_CustomPropertyNameExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a &quot;(property) : (value)&quot; declaration..
        /// </summary>
        internal static string ParseErrorType_DeclarationExpected {
            get {
                return ResourceManager.GetString("ParseErrorType_DeclarationExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a character encoding string after the &quot;@charset&quot;..
        /// </summary>
        internal static string ParseErrorType_EncodingMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_EncodingMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a comma between function arguments..
        /// </summary>
        internal static string ParseErrorType_FunctionArgumentCommaMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_FunctionArgumentCommaMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a function argument..
        /// </summary>
        internal static string ParseErrorType_FunctionArgumentMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_FunctionArgumentMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing an identifier name after the &apos;#&apos;..
        /// </summary>
        internal static string ParseErrorType_IdMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_IdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &quot;important&quot; after the &apos;!&apos;..
        /// </summary>
        internal static string ParseErrorType_ImportantMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_ImportantMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a name after &quot;@keyframes&quot;..
        /// </summary>
        internal static string ParseErrorType_KeyFrameBlockNameMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_KeyFrameBlockNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a keyframes selector..
        /// </summary>
        internal static string ParseErrorType_KeyFramesSelectorExpected {
            get {
                return ResourceManager.GetString("ParseErrorType_KeyFramesSelectorExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a media expression..
        /// </summary>
        internal static string ParseErrorType_MediaExpressionExpected {
            get {
                return ResourceManager.GetString("ParseErrorType_MediaExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a media type..
        /// </summary>
        internal static string ParseErrorType_MediaTypeMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_MediaTypeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing an opening brace (&apos;{&apos;)..
        /// </summary>
        internal static string ParseErrorType_OpenCurlyBraceMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_OpenCurlyBraceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing an opening brace (&apos;{&apos;) after the selector in the style rule..
        /// </summary>
        internal static string ParseErrorType_OpenCurlyBraceMissingForRule {
            get {
                return ResourceManager.GetString("ParseErrorType_OpenCurlyBraceMissingForRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a property name before the colon (&apos;:&apos;) in the &quot;(property) : (value)&quot; declaration..
        /// </summary>
        internal static string ParseErrorType_PropertyNameMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_PropertyNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character sequence in property value..
        /// </summary>
        internal static string ParseErrorType_PropertyValueExpected {
            get {
                return ResourceManager.GetString("ParseErrorType_PropertyValueExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a property value in the &quot;(property) : (value)&quot; declaration..
        /// </summary>
        internal static string ParseErrorType_PropertyValueMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_PropertyValueMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a pseudo-class name after the &apos;:&apos;..
        /// </summary>
        internal static string ParseErrorType_PseudoClassNameMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_PseudoClassNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a pseudo-element name after the &apos;::&apos;..
        /// </summary>
        internal static string ParseErrorType_PseudoElementNameMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_PseudoElementNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a selector after a combinator in the style rule..
        /// </summary>
        internal static string ParseErrorType_SelectorAfterCombineOperatorMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_SelectorAfterCombineOperatorMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a selector after the comma (&apos;,&apos;) in a selector group..
        /// </summary>
        internal static string ParseErrorType_SelectorAfterCommaMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_SelectorAfterCommaMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a selector before a combinator in the style rule..
        /// </summary>
        internal static string ParseErrorType_SelectorBeforeCombineOperatorMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_SelectorBeforeCombineOperatorMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a selector before the comma (&apos;,&apos;) in a selector group..
        /// </summary>
        internal static string ParseErrorType_SelectorBeforeCommaMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_SelectorBeforeCommaMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a selector in the style rule..
        /// </summary>
        internal static string ParseErrorType_SelectorBeforeRuleBlockMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_SelectorBeforeRuleBlockMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a selector for the style rule..
        /// </summary>
        internal static string ParseErrorType_SimpleSelectorExpected {
            get {
                return ResourceManager.GetString("ParseErrorType_SimpleSelectorExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected &apos;@&apos; block in the style rule..
        /// </summary>
        internal static string ParseErrorType_UnexpectedAtDirective {
            get {
                return ResourceManager.GetString("ParseErrorType_UnexpectedAtDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected &apos;!&apos; after the property value. Only one &apos;!&apos; is allowed..
        /// </summary>
        internal static string ParseErrorType_UnexpectedBangInProperty {
            get {
                return ResourceManager.GetString("ParseErrorType_UnexpectedBangInProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected &apos;!&apos; in the selector value. Only one &apos;!&apos; is allowed..
        /// </summary>
        internal static string ParseErrorType_UnexpectedBangInSelector {
            get {
                return ResourceManager.GetString("ParseErrorType_UnexpectedBangInSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a media query or opening brace (&apos;{&apos;)..
        /// </summary>
        internal static string ParseErrorType_UnexpectedMediaQueryToken_Block {
            get {
                return ResourceManager.GetString("ParseErrorType_UnexpectedMediaQueryToken_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a media query or semicolon (&apos;;&apos;)..
        /// </summary>
        internal static string ParseErrorType_UnexpectedMediaQueryToken_Line {
            get {
                return ResourceManager.GetString("ParseErrorType_UnexpectedMediaQueryToken_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character sequence..
        /// </summary>
        internal static string ParseErrorType_UnexpectedToken {
            get {
                return ResourceManager.GetString("ParseErrorType_UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a URL after &quot;@import&quot;..
        /// </summary>
        internal static string ParseErrorType_UrlImportMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_UrlImportMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a namespace definition after &quot;@namespace&quot;..
        /// </summary>
        internal static string ParseErrorType_UrlNamespaceMissing {
            get {
                return ResourceManager.GetString("ParseErrorType_UrlNamespaceMissing", resourceCulture);
            }
        }
    }
}
