trigger:
  batch: true
  branches:
    include:
    - main
    - release/*.*

variables:
  # Cannot use key:value syntax in root defined variables
  - name: _TeamName
    value: DotNetCore
  - name: TeamName
    value: DotNetCore
  - name: _PublishUsingPipelines
    value: true
  - name: _DotNetArtifactsCategory
    value: .NETCore
  - name: Codeql.Enabled
    value: true
  - template: /eng/common/templates-official/variables/pool-providers.yml@self
  - group: DotNet-AspNet-SDLValidation-Params

resources:
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    sdl:
      sourceAnalysisPool:
        name: $(DncEngInternalBuildPool)
        image: 1es-windows-2022-pt
        os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: build
      displayName: Build
      jobs:
      - template: /eng/common/templates-official/jobs/jobs.yml@self
        parameters:
          enableMicrobuild: true
          enablePublishBuildArtifacts: true
          enablePublishTestResults: true
          enablePublishBuildAssets: true
          enablePublishUsingPipelines: ${{ variables._PublishUsingPipelines }}
          enableSourceBuild: true
          enableTelemetry: true
          helixRepo: dotnet/xdt
          jobs:
          - job: Windows_NT
            pool:
              name: $(DncEngInternalBuildPool)
              image: 1es-windows-2022-pt

            variables:
            - _Script: eng\common\cibuild.cmd
            - _ValidateSdkArgs: ''
            - _InternalBuildArgs: ''

            # DotNet-Symbol-Server-Pats provides: microsoft-symbol-server-pat, symweb-symbol-server-pat
            # Publish-Build-Assets provides: MaestroAccessToken, BotAccount-dotnet-maestro-bot-PAT
            - group: DotNet-Symbol-Server-Pats
            - group: Publish-Build-Assets
            - _InternalBuildArgs: /p:DotNetSignType=$(_SignType) /p:TeamName=$(_TeamName)
                /p:DotNetPublishUsingPipelines=$(_PublishUsingPipelines)
                /p:DotNetArtifactsCategory=$(_DotNetArtifactsCategory)
                /p:DotNetSymbolServerTokenMsdl=$(microsoft-symbol-server-pat)
                /p:DotNetSymbolServerTokenSymWeb=$(symweb-symbol-server-pat)
                /p:OfficialBuildId=$(BUILD.BUILDNUMBER)

            strategy:
              matrix:
                Build_Release:
                  _BuildConfig: Release
                  _PublishType: blob
                  _SignType: real
                  # _Script: eng\validate-sdk.cmd
                  # _ValidateSdkArgs: -gitHubPat $(BotAccount-dotnet-maestro-bot-PAT) -barToken $(MaestroAccessToken)
            steps:
            - checkout: self
              clean: true
            # Use utility script to run script command dependent on agent OS.
            - script: $(_Script)
                -configuration $(_BuildConfig) 
                -prepareMachine
                $(_InternalBuildArgs)
                $(_ValidateSdkArgs)
              displayName: Windows Build / Publish

    - template: eng/common/templates-official/post-build/post-build.yml@self
      parameters:
        publishDependsOn:
        - Validate
        # This is to enable SDL runs part of Post-Build Validation Stage
        SDLValidationParameters:
          enable: true
          continueOnError: false
          params: ' -SourceToolsList @("policheck","credscan")
          -ArtifactToolsList @("binskim")
          -BinskimAdditionalRunConfigParams @("IgnorePdbLoadError < True","Recurse < True")
          -TsaInstanceURL $(_TsaInstanceURL)
          -TsaProjectName $(_TsaProjectName)
          -TsaNotificationEmail $(_TsaNotificationEmail)
          -TsaCodebaseAdmin $(_TsaCodebaseAdmin)
          -TsaBugAreaPath $(_TsaBugAreaPath)
          -TsaIterationPath $(_TsaIterationPath)
          -TsaRepositoryName "xdt"
          -TsaCodebaseName "xdt"
          -TsaPublish $True'
