// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
// ------------------------------------------------------------------------------
// Changes to this file must follow the http://aka.ms/api-review process.
// ------------------------------------------------------------------------------
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Security.AllowPartiallyTrustedCallers]
[assembly: System.Reflection.AssemblyTitle("System.IO.Packaging")]
[assembly: System.Reflection.AssemblyDescription("System.IO.Packaging")]
[assembly: System.Reflection.AssemblyDefaultAlias("System.IO.Packaging")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyProduct("Microsoft® .NET Framework")]
[assembly: System.Reflection.AssemblyCopyright("© Microsoft Corporation.  All rights reserved.")]
[assembly: System.Reflection.AssemblyFileVersion("4.6.26515.06")]
[assembly: System.Reflection.AssemblyInformationalVersion("4.6.26515.06 @BuiltBy: dlab-DDVSOWINAGE059 @Branch: release/2.1 @SrcCode: https://github.com/dotnet/corefx/tree/30ab651fcb4354552bd4891619a0bdd81e0ebdbf")]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyMetadata(".NETFrameworkAssembly", "")]
[assembly: System.Reflection.AssemblyMetadata("Serviceable", "True")]
[assembly: System.Reflection.AssemblyMetadata("PreferInbox", "True")]
[assembly: System.Reflection.AssemblyVersionAttribute("4.0.3.0")]
[assembly: System.Runtime.CompilerServices.ReferenceAssembly]
[assembly: System.Reflection.AssemblyFlagsAttribute((System.Reflection.AssemblyNameFlags)0x70)]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.FileFormatException))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.CompressionOption))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.EncryptionOption))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.Package))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.PackagePart))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.PackagePartCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.PackageProperties))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.PackageRelationship))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.PackageRelationshipCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.PackageRelationshipSelector))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.PackageRelationshipSelectorType))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.PackUriHelper))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.TargetMode))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.ZipPackage))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.ZipPackagePart))]
