//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.SolutionPersistence {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.SolutionPersistence.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move a folder to a child folder..
        /// </summary>
        internal static string CannotMoveFolderToChildFolder {
            get {
                return ResourceManager.GetString("CannotMoveFolderToChildFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple default project types defined..
        /// </summary>
        internal static string DuplicateDefaultProjectType {
            get {
                return ResourceManager.GetString("DuplicateDefaultProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate file extension &apos;{0}&apos; for project type &apos;{1}&apos;..
        /// </summary>
        internal static string DuplicateExtension_Args2 {
            get {
                return ResourceManager.GetString("DuplicateExtension_Args2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate item &apos;{0}&apos; of type &apos;{1}&apos;..
        /// </summary>
        internal static string DuplicateItemRef_Args2 {
            get {
                return ResourceManager.GetString("DuplicateItemRef_Args2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element with the same key already exists..
        /// </summary>
        internal static string DuplicateKey {
            get {
                return ResourceManager.GetString("DuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate name &apos;{0}&apos; for project type &apos;{1}&apos;..
        /// </summary>
        internal static string DuplicateName_Args2 {
            get {
                return ResourceManager.GetString("DuplicateName_Args2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name &apos;{0}&apos; already exists in the solution folder..
        /// </summary>
        internal static string DuplicateProjectName_Arg1 {
            get {
                return ResourceManager.GetString("DuplicateProjectName_Arg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project path &apos;{0}&apos; already exists in the solution..
        /// </summary>
        internal static string DuplicateProjectPath_Arg1 {
            get {
                return ResourceManager.GetString("DuplicateProjectPath_Arg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate project type id &apos;{0}&apos; for project type &apos;{1}&apos;..
        /// </summary>
        internal static string DuplicateProjectTypeId_Args2 {
            get {
                return ResourceManager.GetString("DuplicateProjectTypeId_Args2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid syntax for solution configuration &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidConfiguration_Args1 {
            get {
                return ResourceManager.GetString("InvalidConfiguration_Args1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only ASCII, UTF-8, and Unicode encodings are supported for serializing &apos;.sln&apos; files..
        /// </summary>
        internal static string InvalidEncoding {
            get {
                return ResourceManager.GetString("InvalidEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution folder path &apos;{0}&apos; must start and end with &apos;/&apos;..
        /// </summary>
        internal static string InvalidFolderPath_Args1 {
            get {
                return ResourceManager.GetString("InvalidFolderPath_Args1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &apos;{0}&apos; not found..
        /// </summary>
        internal static string InvalidFolderReference_Args1 {
            get {
                return ResourceManager.GetString("InvalidFolderReference_Args1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing or invalid &apos;{0}&apos; item in type &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidItemRef_Args2 {
            get {
                return ResourceManager.GetString("InvalidItemRef_Args2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular dependency found for &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidLoop_Args1 {
            get {
                return ResourceManager.GetString("InvalidLoop_Args1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model does not belong to this solution..
        /// </summary>
        internal static string InvalidModelItem {
            get {
                return ResourceManager.GetString("InvalidModelItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names cannot:
        ///- contain any of the following characters: / ? : \ * &quot; &lt; &gt; |
        ///- contain control characters
        ///- be system reserved names, including &apos;CON&apos;, &apos;AUX&apos;, &apos;PRN&apos;, &apos;COM1&apos; or &apos;LPT2&apos;
        ///- be &apos;.&apos; or &apos;..&apos;.
        /// </summary>
        internal static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Project &apos;{0}&apos; not found.&quot;.
        /// </summary>
        internal static string InvalidProjectReference_Args1 {
            get {
                return ResourceManager.GetString("InvalidProjectReference_Args1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing or invalid project type guid..
        /// </summary>
        internal static string InvalidProjectType {
            get {
                return ResourceManager.GetString("InvalidProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectType &apos;{0}&apos; not found..
        /// </summary>
        internal static string InvalidProjectTypeReference_Args1 {
            get {
                return ResourceManager.GetString("InvalidProjectTypeReference_Args1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing or invalid scope..
        /// </summary>
        internal static string InvalidScope {
            get {
                return ResourceManager.GetString("InvalidScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid version &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidVersion_Args1 {
            get {
                return ResourceManager.GetString("InvalidVersion_Args1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing display name..
        /// </summary>
        internal static string MissingDisplayName {
            get {
                return ResourceManager.GetString("MissingDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing project path..
        /// </summary>
        internal static string MissingPath {
            get {
                return ResourceManager.GetString("MissingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing project id..
        /// </summary>
        internal static string MissingProjectId {
            get {
                return ResourceManager.GetString("MissingProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project attribute is empty..
        /// </summary>
        internal static string MissingProjectValue {
            get {
                return ResourceManager.GetString("MissingProjectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing section name..
        /// </summary>
        internal static string MissingSectionName {
            get {
                return ResourceManager.GetString("MissingSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a solution file..
        /// </summary>
        internal static string NotSolution {
            get {
                return ResourceManager.GetString("NotSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error..
        /// </summary>
        internal static string SyntaxError {
            get {
                return ResourceManager.GetString("SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file version &apos;{0}&apos; is unsupported..
        /// </summary>
        internal static string UnsupportedVersion_Args1 {
            get {
                return ResourceManager.GetString("UnsupportedVersion_Args1", resourceCulture);
            }
        }
    }
}
