// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;

namespace Microsoft.DotNet.SourceBuild.Tasks
{
    /// <summary>
    /// Normalizes IL files generated by ILDasm to ensure consistent output across
    /// different platforms, ILDasm versions, and runtime environments.
    /// </summary>
    public partial class NormalizeIL : Task
    {
        [Required]
        public ITaskItem[] ILFileNames { get; set; } = null!;

        [GeneratedRegex(@"//\s*-nan\(ind\)")]
        private static partial Regex NanIndRegex();

        public override bool Execute()
        {
            Log.LogMessage(MessageImportance.High, "STARTING REMOVE RESOURCES");

            foreach (var ilFile in ILFileNames)
            {
                var lines = File.ReadAllLines(ilFile.ItemSpec);
                var outputLines = new List<string>();

                bool insideResource = false;
                bool inHeaderSection = true;
                foreach (var line in lines)
                {
                    var trimmedLine = line.TrimStart();

                    // Once we hit an IL directive (starts with '.'), we're past the header
                    if (trimmedLine.StartsWith("."))
                    {
                        inHeaderSection = false;
                    }

                    // Skip Win32 resource file warning comments generated by ILDasm on Windows
                    if (trimmedLine.StartsWith("// WARNING: Created Win32 resource file"))
                    {
                        continue;
                    }

                    // Skip Image base comments that appear after IL directives (not in PE header)
                    // TODO: Remove once https://github.com/dotnet/runtime/issues/122912 is fixed and picked up
                    if (!inHeaderSection && trimmedLine.StartsWith("// Image base:"))
                    {
                        continue;
                    }

                    // Skip ILDasm version line that varies between different ILDasm versions.
                    // This helps make it easier to spot real differences when regenerating IL files.
                    // If the version is needed, look at the Version.Details at the point in time
                    // when the IL files were checked in/generated.
                    if (trimmedLine.StartsWith("//  .NET IL Disassembler.  Version"))
                    {
                        continue;
                    }

                    if (line.StartsWith(".mresource") || line.Contains(" static pinvokeimpl"))
                    {
                        insideResource = true;
                    }
                    if (insideResource && trimmedLine.StartsWith("}"))
                    {
                        insideResource = false;
                    }
                    else if (!insideResource)
                    {
                        // Normalize NaN formatting: Windows uses "-nan(ind)" while Linux uses "-nan"
                        // TODO: Remove once https://github.com/dotnet/runtime/issues/122976 is fixed.
                        string normalizedLine = NanIndRegex().Replace(line, "// -nan");
                        outputLines.Add(normalizedLine);
                    }
                }
                File.WriteAllLines(ilFile.ItemSpec, outputLines);
            }

            return true;
        }
    }
}
