parameters:
  name: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      name: Hosted macOS
    ${{ if ne(variables['System.TeamProject'], 'public') }}:
      name: Hosted Mac internal
  strategy:
    matrix: 
      debug:
        _BuildConfig: Debug
      release:
        _BuildConfig: Release
  workspace:
    clean: all
  variables: 
    CommonMSBuildArgs: >-
      /p:Configuration=$(_BuildConfig)
      /p:PortableBuild=true
  steps:

  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - task: NuGetAuthenticate@0

  - ${{ if ne(variables['System.TeamProject'], 'public') }}:
    - task: Bash@3
      displayName: Setup Private Feeds Credentials
      inputs:
        filePath: $(Build.SourcesDirectory)/eng/common/SetupNugetSources.sh
        arguments: $(Build.SourcesDirectory)/NuGet.config $Token
      condition: ne(variables['Agent.OS'], 'Windows_NT')
      env:
        Token: $(dn-bot-dnceng-artifact-feeds-rw)

  - script: >-
      $(Build.SourcesDirectory)/build.sh --ci --test
      /p:OfficialBuildId=$(OfficialBuildId)
      /p:StripSymbols=true
      $(CommonMSBuildArgs)
    displayName: Build 
    condition: succeeded()

  - template: steps/upload-job-artifacts.yml
    parameters:
      name: ${{ parameters.name }}
