parameters:
  additionalMSBuildArguments: ''
  displayName: ''
  publishRidAgnosticPackages: false
  targetArchitecture: null
  timeoutInMinutes: 120
  codeql: false
jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
  pool:
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      name: NetCore-Public
      demands: ImageOverride -equals windows.vs2022.amd64.open
    ${{ if ne(variables['System.TeamProject'], 'public') }}:
      name: NetCore1ESPool-Internal
      demands: ImageOverride -equals windows.vs2022.amd64
  strategy:
    matrix:
      release:
        _BuildConfig: Release
      ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
        debug:
          _BuildConfig: Debug
  workspace:
    clean: all
  variables:
    CommonMSBuildArgs: >-
      -c $(_BuildConfig) /p:TargetArchitecture=${{ parameters.targetArchitecture }} /p:DotNetSignType=$(_SignType)
    ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
      InternalMSBuildArgs: >-
        /p:OfficialBuildId=$(Build.BuildNumber) /p:DotNetPublishUsingPipelines=true /p:Test=false
    ${{ else }}:
      InternalMSBuildArgs: ''
    Codeql.Enabled: ${{ parameters.codeql }}
  steps:
  - powershell: Remove-Item -Recurse -ErrorAction Ignore "$env:LocalAppData\NuGet\v3-cache"
    displayName: Clear NuGet http cache (if exists)
  - ${{ if ne(variables['System.TeamProject'], 'public') }}:
    - task: PowerShell@2
      displayName: Setup Private Feeds Credentials
      condition: eq(variables['Agent.OS'], 'Windows_NT')
      inputs:
        filePath: $(Build.SourcesDirectory)/eng/common/SetupNugetSources.ps1
        arguments: -ConfigFile $(Build.SourcesDirectory)/NuGet.config -Password $Env:Token
      env:
        Token: $(dn-bot-dnceng-artifact-feeds-rw)
    - task: NuGetAuthenticate@1
  - script: >-
      eng\common\cibuild.cmd $(CommonMSBuildArgs) $(InternalMSBuildArgs)
    displayName: Build
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - template: /eng/common/templates/steps/generate-sbom.yml@self
      parameters:
        name: Generate_SBOM_${{ parameters.name }}
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest'), ne(variables['DisableVSPublish'], 'true'), eq(variables['_BuildConfig'], 'Release')) }}:
    - task: NuGetToolInstaller@1
      displayName: 'Install NuGet.exe'
    - task: NuGetCommand@2
      displayName: Push Visual Studio NuPkgs
      inputs:
        command: push
        packagesToPush: $(Build.SourcesDirectory)/artifacts/packages/$(_BuildConfig)/*/VS.Redist.Common.NETCoreCheck.*.nupkg
        nuGetFeedType: external
        publishFeedCredentials: 'DevDiv - VS package feed'
      condition: succeeded()
    - ${{ if eq(parameters.targetArchitecture, 'x64') }}:
      - task: NuGetCommand@2
        displayName: Push Visual Studio NuPkgs
        inputs:
          command: push
          packagesToPush: $(Build.SourcesDirectory)/artifacts/packages/$(_BuildConfig)/*/VS.Redist.Common.NetCore.Launcher.*.nupkg
          nuGetFeedType: external
          publishFeedCredentials: 'DevDiv - VS package feed'
        condition: succeeded()
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - powershell: |
        $folderExists = Test-Path -Path "$(Build.SourcesDirectory)/artifacts/packages/$(_BuildConfig)"
        Write-Output "##vso[task.setvariable variable=ArtifactsPackagesFolderExists]$folderExists"
      displayName: Detect Packages subdirectory
    - task: CopyFiles@2
      displayName: Prepare job-specific Artifacts subdirectory
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/artifacts/packages/$(_BuildConfig)'
        Contents: |
          Shipping/**/*
          NonShipping/**/*
        TargetFolder: '$(Build.StagingDirectory)/Artifacts/${{ parameters.name }}'
        CleanTargetFolder: true
      condition: and(succeeded(), eq(variables._BuildConfig, 'Release'), eq(variables['ArtifactsPackagesFolderExists'], True))
    - powershell: |
        $folderExists = Test-Path -Path "$(Build.StagingDirectory)/Artifacts"
        Write-Output "##vso[task.setvariable variable=StagingArtifactsFolderExist]$folderExists"
      displayName: Detect Staged Artifacts subdirectory
    - task: PublishBuildArtifacts@1
      displayName: Publish Artifacts
      inputs:
        pathToPublish: '$(Build.StagingDirectory)/Artifacts'
        artifactName: IntermediateUnsignedArtifacts
        artifactType: container
      condition: and(succeeded(), eq(variables._BuildConfig, 'Release'), eq(variables['StagingArtifactsFolderExist'], True))
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - task: CopyFiles@2
      displayName: Prepare job-specific PdbArtifacts subdirectory
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/artifacts/SymStore/$(_BuildConfig)'
        Contents: |
          **/*
        TargetFolder: '$(Build.StagingDirectory)/PdbArtifacts/${{ parameters.name }}'
        CleanTargetFolder: true
      condition: and(succeeded(), eq(variables._BuildConfig, 'Release'))
    - task: PublishBuildArtifacts@1
      displayName: Publish PdbArtifacts
      inputs:
        pathToPublish: '$(Build.StagingDirectory)/PdbArtifacts'
        artifactName: PdbArtifacts
        artifactType: container
      condition: and(succeeded(), eq(variables._BuildConfig, 'Release'))
  - ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
    - task: PublishTestResults@2
      displayName: Publish Test Results
      inputs:
        testResultsFormat: 'xUnit'
        testResultsFiles: '*.xml'
        searchFolder: '$(Build.SourcesDirectory)/artifacts/TestResults/$(_BuildConfig)'
        mergeTestResults: true
        testRunTitle: ${{ parameters.name }}-$(_BuildConfig)
      continueOnError: true
      condition: always()
  - task: CopyFiles@2
    displayName: Prepare BuildLogs staging directory
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
        **/*.log
        **/*.binlog
      TargetFolder: '$(Build.StagingDirectory)/BuildLogs'
      CleanTargetFolder: true
    continueOnError: true
    condition: succeededOrFailed()
  - task: PublishBuildArtifacts@1
    displayName: Publish BuildLogs
    inputs:
      PathtoPublish: '$(Build.StagingDirectory)/BuildLogs'
      ArtifactName: Logs-${{ parameters.name }}-$(_BuildConfig)
    continueOnError: true
    condition: succeededOrFailed()