trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
  paths:
    exclude:
    - README.md
    - docs/*

pr:
  branches:
    include:
    - main
    - release/*
  paths:
    exclude:
    - README.md
    - docs/*

variables:
- template: /azure-pipelines/templates/variables/common.yml

stages:
- template: /azure-pipelines/templates/stages/build.yml
  parameters:
    engCommonTemplatesDir: ${{ variables.EngCommonTemplatesDir }}
