trigger:
  batch: true
  branches:
    include:
    - main
    - release/*

pr:
  branches:
    include:
    - main
    - release/*

variables:
- template: /azure-pipelines/templates/variables/common.yml

stages:
- template: /azure-pipelines/templates/stages/build.yml
  parameters:
    engCommonTemplatesDir: ${{ variables.EngCommonTemplatesDir }}
