trigger: none
pr: none

variables:
- template: /azure-pipelines/templates/variables/common.yml

resources:
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release

extends:
  template: azure-pipelines/MicroBuild.1ES.Unofficial.yml@MicroBuildTemplate
  parameters:
    sdl:
      sourceAnalysisPool:
        name: $(DncEngInternalBuildPool)
        image: 1es-windows-2022
        os: windows
    pool:
      name: $(DncEngInternalBuildPool)
      image: 1es-ubuntu-2204
      os: linux
    stages:
    - template: /azure-pipelines/templates/stages/build.yml@self
      parameters:
        engCommonTemplatesDir: ${{ variables.EngCommonTemplatesDir }}
