parameters:
  - name: BuildRTM
    type: boolean
  - name: SigningType
    displayName: Type of signing to use
    type: string

steps:
  - task: PowerShell@1
    inputs:
      scriptName: "$(Build.Repository.LocalPath)\\configure.ps1"
      arguments: "-Force"
    displayName: "Run Configure.ps1"

  - task: PowerShell@1
    inputs:
      scriptName: "$(Build.Repository.LocalPath)\\scripts\\cibuild\\ConfigureVstsBuild.ps1"
      arguments: >-
        -BuildRTM $(BuildRTM)
        -RepositoryPath $(Build.Repository.LocalPath)
        -BranchName $(SourceBranch)
        -CommitHash $(Build.SourceVersion)
        -BuildNumber $(Build.BuildNumber)
        -BuildInfoDirectory $(Build.StagingDirectory)\BuildInfo
    displayName: "Configure VSTS CI Environment"

  - task: PowerShell@1
    displayName: "Print Environment Variables"
    inputs:
      scriptType: "inlineScript"
      inlineScript: |
        Get-ChildItem Env: | Sort-Object Name | Format-Table -Wrap -AutoSize

  # NuGet.Client's official repo is on github, hence the source link metadata should use the github URL.
  # However, our official builds are built from a mirror in Azure DevOps, hence without any extra help, the SourceLink.GitHub package
  # won't be able to determine the URL to embed in the pdbs.
  # Therefore, we need to add the GitHub repo URL as a remote, and tell SourceLink.GitHub what that remote name is.
  # We do this even when github is the origin URL, to avoid warnings in the CI logs.
  - task: PowerShell@1
    displayName: "Prepare for source link"
    inputs:
      scriptType: "inlineScript"
      inlineScript: |
        try {
          $nugetUrl = "https://github.com/NuGet/NuGet.Client.git"
          if (@(& git remote).Contains("github"))
          {
            $currentGitHubRemoteUrl = & git remote get-url github
            Write-Host "Current github remote URL: $currentGitHubRemoteUrl"
            if ($currentGitHubRemoteUrl -ne $nugetUrl)
            {
              Write-Host "git remote set-url github $nugetUrl"
              & git remote set-url github $nugetUrl
            }
            else
            {
              Write-Host "Git remote url already correct"
            }
          }
          else
          {
            Write-Host "git remote add github $nugetUrl"
            & git remote add github $nugetUrl
          }
        } catch {
          Write-Host "##vso[task.LogIssue type=error;]$Error[0]"
          exit 1
        }

  - task: CodeQL3000Init@0
    displayName: Initialize CodeQL
    condition: "and(succeeded(), eq(variables['BuildRTM'], 'true'), eq(variables['Codeql.Enabled'], 'true'))"

  - task: MSBuild@1
    displayName: "Restore"
    inputs:
      solution: "build\\build.proj"
      configuration: "$(BuildConfiguration)"
      msbuildArguments: "/restore:false /target:RestoreVS /property:BuildNumber=$(BuildNumber) /property:BuildRTM=$(BuildRTM) /property:IncludeApex=true /binarylogger:$(Build.StagingDirectory)\\binlog\\01.Restore.binlog"

  - task: CmdLine@2
    displayName: "Restore packages to publish to the .NET Core build asset registry (BAR)"
    inputs:
      script: dotnet restore $(Build.Repository.LocalPath)\build\publish.proj -binarylogger:$(Build.StagingDirectory)\\binlog\\01.Restore-publish.binlog"
      workingDirectory: cli
      failOnStderr: true
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_MULTILEVEL_LOOKUP: true
    condition: "and(succeeded(), eq(variables['BuildRTM'], 'false'))"

  - task: PowerShell@1
    displayName: "Set IncludeApex variable"
    name: "includeapex"
    inputs:
      scriptType: "inlineScript"
      inlineScript: |
        try {
          $IncludeApex = -not [bool]::Parse($env:BuildRTM)
          Write-Host "IncludeApex URL: $IncludeApex"
          Write-Host "##vso[task.setvariable variable=IncludeApex]$IncludeApex"
        } catch {
          Write-Host "##vso[task.LogIssue type=error;]Unable to set IncludeApex: $_"
          exit 1
        }

  - task: MSBuild@1
    displayName: "Build"
    inputs:
      solution: "build\\build.proj"
      configuration: "$(BuildConfiguration)"
      msbuildArguments: "/restore:false /target:BuildNoVSIX /property:BuildRTM=$(BuildRTM) /property:BuildNumber=$(BuildNumber) /property:GitRepositoryRemoteName=github /property:IncludeApex=$(IncludeApex) /binarylogger:$(Build.StagingDirectory)\\binlog\\02.Build.binlog /property:MicroBuild_SigningEnabled=false"

  # NuGet.exe embeds its own satellite resources, but satellite resources are built after the main assembly.
  # This means on the first build it's missing the resources, so we have to build nuget.exe a second time.
  - task: MSBuild@1
    displayName: "Build localized NuGet.exe"
    inputs:
      solution: "src\\NuGet.Clients\\NuGet.CommandLine"
      configuration: "$(BuildConfiguration)"
      msbuildArguments: "/restore:false /property:BuildProjectReferences=false /property:BuildRTM=$(BuildRTM) /property:BuildNumber=$(BuildNumber) /property:GitRepositoryRemoteName=github /binarylogger:$(Build.StagingDirectory)\\binlog\\02a.Build_NuGet.exe.binlog /property:MicroBuild_SigningEnabled=false"

  - task: CodeQL3000Finalize@0
    displayName: Finalize CodeQL
    condition: "and(succeeded(), eq(variables['BuildRTM'], 'true'), eq(variables['Codeql.Enabled'], 'true'))"

  - task: MSBuild@1
    displayName: "Pack Nupkgs"
    inputs:
      solution: "build\\build.proj"
      configuration: "$(BuildConfiguration)"
      msbuildArguments: "/restore:false /target:Pack /property:BuildRTM=$(BuildRTM) /property:ExcludeTestProjects=$(BuildRTM) /property:BuildNumber=$(BuildNumber) /binarylogger:$(Build.StagingDirectory)\\binlog\\11.Pack.binlog /property:MicroBuild_SigningEnabled=false"

  - task: PowerShell@1
    displayName: "Check expected packages exist for publishing"
    name: "EnsureAllPackagesExist"
    inputs:
      scriptName: "$(Build.Repository.LocalPath)\\scripts\\utils\\EnsureAllPackagesExist.ps1"
      arguments: "-BuildRTM:$$(BuildRTM) -NupkgOutputPath '$(Build.Repository.LocalPath)\\artifacts\\$(NupkgOutputDir)'"

  - task: MSBuild@1
    displayName: "Ensure all Nupkgs and Symbols are created"
    inputs:
      solution: "build\\build.proj"
      configuration: "$(BuildConfiguration)"
      msbuildArguments: "/restore:false /target:EnsurePackagesExist /property:ExcludeTestProjects=$(BuildRTM) /binarylogger:$(Build.StagingDirectory)\\binlog\\12.EnsurePackagesExist.binlog"

  - task: MSBuild@1
    displayName: "Pack VSIX"
    inputs:
      solution: "build\\build.proj"
      configuration: "$(BuildConfiguration)"
      msbuildArguments: "/restore:false /target:BuildVSIX /property:BuildRTM=$(BuildRTM) /property:ExcludeTestProjects=$(BuildRTM) /property:IsCIBuild=true /binarylogger:$(Build.StagingDirectory)\\binlog\\13.PackVSIX.binlog"
    condition: "and(succeeded(),eq(variables['BuildRTM'], 'false'))"
  - ${{ if not(parameters.BuildRTM)}}:
      - template: /eng/common/templates-official/steps/generate-sbom.yml@self
        parameters:
          PackageName: "NuGet.Client"
          PackageVersion: "$(SemanticVersion)"
          publishArtifacts: false

  - task: MSBuild@1
    displayName: "Generate Build Tools package"
    inputs:
      solution: "setup\\Microsoft.VisualStudio.NuGet.BuildTools\\Microsoft.VisualStudio.NuGet.BuildTools.vsmanproj"
      configuration: "$(BuildConfiguration)"
      msbuildArguments: "/property:BuildNumber=$(BuildNumber) /property:IsVsixBuild=true /binarylogger:$(Build.StagingDirectory)\\binlog\\14.BuildToolsVSIX.binlog"
    condition: "and(succeeded(), eq(variables['BuildRTM'], 'false'))"

  - task: MSBuild@1
    displayName: "Sign"
    inputs:
      solution: "build\\sign.proj"
      configuration: "$(BuildConfiguration)"
      msbuildArguments: "/restore /p:DryRunSigning=false /p:DotNetSignType=${{parameters.SigningType}} /p:SigningLogDirectory=$(Build.StagingDirectory)\\binlog /binarylogger:$(Build.StagingDirectory)\\binlog\\15.Sign.binlog"

  - task: NuGetToolInstaller@1
    displayName: Use NuGet 6.x
    inputs:
      versionSpec: 6.x

  - task: NuGetCommand@2
    displayName: "Verify Nupkg Signatures"
    inputs:
      command: "custom"
      arguments: "verify -Signatures $(Build.Repository.LocalPath)\\artifacts\\$(NupkgOutputDir)\\*.nupkg"

  - task: MicroBuildCodesignVerify@3
    displayName: Verify Assembly Signatures and StrongName for the nupkgs
    inputs:
      TargetFolders: '$(Build.Repository.LocalPath)\\artifacts\\$(NupkgOutputDir)'

  - task: MicroBuildCodesignVerify@3
    displayName: Verify Assembly Signatures and StrongName for the VSIX & exes
    inputs:
      TargetFolders: '$(Build.Repository.LocalPath)\\artifacts\\VS15'
      ApprovalListPathForCerts: '$(Build.Repository.LocalPath)\\build\\ignorecodesign.csv'
      ApprovalListPathForSigs: '$(Build.Repository.LocalPath)\\build\\ignorecodesign.csv'

  - task: MSBuild@1
    displayName: "Generate VSMAN file for NuGet Core VSIX"
    inputs:
      solution: "setup\\Microsoft.VisualStudio.NuGet.Core\\Microsoft.VisualStudio.NuGet.Core.vsmanproj"
      configuration: "$(BuildConfiguration)"
      msbuildArguments: "/property:ManifestDirPath=$(Build.ArtifactStagingDirectory)/sbom /binarylogger:$(Build.StagingDirectory)\\binlog\\16.GenerateVSManifestForVSIX.binlog"
    condition: "and(succeeded(),eq(variables['BuildRTM'], 'false'))"

  - task: MSBuild@1
    displayName: "Generate VSMAN file for Build Tools VSIX"
    inputs:
      solution: "setup\\Microsoft.VisualStudio.NuGet.BuildTools\\Microsoft.VisualStudio.NuGet.BuildTools.vsmanproj"
      configuration: "$(BuildConfiguration)"
      msbuildArguments: "/property:IsVsixBuild=false /property:ManifestDirPath=$(Build.ArtifactStagingDirectory)/sbom /binarylogger:$(Build.StagingDirectory)\\binlog\\17.GenerateVSManifestForToolsVSIX.binlog"
    condition: "and(succeeded(),eq(variables['BuildRTM'], 'false'))"

  - task: NuGetCommand@2
    displayName: "Add the VSEng package source"
    inputs:
      command: "custom"
      arguments: 'sources add -Name VS -Source $(VsPackageFeedUrl) -UserName $(VsPackageFeedUsername) -Password $(VsPackageFeedPassword) -ConfigFile $(System.DefaultWorkingDirectory)\NuGet.config'
    condition: "and(succeeded(), eq(variables['BuildRTM'], 'false'))"

  - task: NuGetCommand@2
    displayName: "Install the NuGet package for building .runsettingsproj files"
    inputs:
      command: "custom"
      arguments: 'install Microsoft.DevDiv.Validation.TestPlatform.Settings.Tasks -Version 1.0.655 -Source $(VsPackageFeedUrl) -ConfigFile $(System.DefaultWorkingDirectory)\NuGet.config -OutputDirectory $(System.DefaultWorkingDirectory)\packages'
    condition: "and(succeeded(), eq(variables['BuildRTM'], 'false'))"

  - task: MSBuild@1
    displayName: "Generate .runsettings files"
    inputs:
      solution: 'build\runsettings.proj'
      msbuildArguments: '/restore:false /property:OutputPath="$(Build.StagingDirectory)\RunSettings" /property:TestDrop="$(RunSettingsDropName)" /property:ProfilingInputsDrop="$(ProfilingInputsDropName)" /binarylogger:$(Build.StagingDirectory)\\binlog\\17.GenerateRunSettings.binlog'
    condition: "and(succeeded(), eq(variables['BuildRTM'], 'false'))"

  - task: PowerShell@1
    displayName: "Copy VS integration test binaries"
    inputs:
      scriptType: "inlineScript"
      inlineScript: |
        try {
          Write-Output "Copying NuGet.OptProf binaries"
          Copy-Item test\NuGet.Tests.Apex\NuGet.OptProf\bin\$(BuildConfiguration) $(Build.StagingDirectory)\RunSettings\NuGet.OptProf\ -Recurse -ErrorAction Stop
          Write-Output "Copying NuGet.Tests.Apex binaries"
          Copy-Item test\NuGet.Tests.Apex\NuGet.Tests.Apex\bin\$(BuildConfiguration) $(Build.StagingDirectory)\RunSettings\NuGet.Tests.Apex\ -Recurse -ErrorAction Stop
          Write-Output "Copying NuGet.Tests.Apex.Daily binaries"
          Copy-Item test\NuGet.Tests.Apex\NuGet.Tests.Apex.Daily\bin\$(BuildConfiguration) $(Build.StagingDirectory)\RunSettings\NuGet.Tests.Apex.Daily\ -Recurse -ErrorAction Stop
        } catch {
          Write-Host "##vso[task.LogIssue type=error;]$_"
          exit 1
        }
    condition: "and(succeeded(), eq(variables['BuildRTM'], 'false'))"

  - task: MSBuild@1
    displayName: "Collect Build Symbols"
    inputs:
      solution: "build\\symbols.proj"
      configuration: "$(BuildConfiguration)"
      msbuildArguments: >-
        /restore:false
        /property:BuildProjectReferences=false
        /property:IsSymbolBuild=true
        /property:BuildRTM=$(BuildRTM)
        /property:SymbolsOutputDirectory=$(Build.StagingDirectory)\\symbolstoindex
        /binarylogger:$(Build.StagingDirectory)\\binlog\\18.CollectBuildSymbols.binlog
      maximumCpuCount: true

  - task: MSBuild@1
    displayName: "LocValidation: Verify VSIX"
    inputs:
      solution: "build\\BuildValidator.proj"
      configuration: "$(BuildConfiguration)"
      msbuildArguments: "/target:ValidateVsix /property:BuildRTM=$(BuildRTM) /property:LogsBasePath=$(Build.StagingDirectory)\\BuildValidatorLogs /property:TempDirectory=$(Agent.TempDirectory) /binarylogger:$(Build.StagingDirectory)\\binlog\\19.ValidateVsixLocalization.binlog"
    condition: "and(succeeded(), eq(variables['BuildRTM'], 'false'))"

  - task: MSBuild@1
    displayName: "LocValidation: Verify Artifacts"
    inputs:
      solution: "build\\BuildValidator.proj"
      configuration: "$(BuildConfiguration)"
      msbuildArguments: "/target:ValidateArtifacts /property:BuildRTM=$(BuildRTM) /property:LogsBasePath=$(Build.StagingDirectory)\\BuildValidatorLogs /property:TempDirectory=$(Agent.TempDirectory) /binarylogger:$(Build.StagingDirectory)\\binlog\\20.ValidateArtifactsLocalization.binlog"
    condition: "and(succeeded(), eq(variables['BuildRTM'], 'false'))"

  - task: CopyFiles@2
    displayName: Copy product to staging directory
    inputs:
      SourceFolder: '$(Build.Repository.LocalPath)\\artifacts\\VS15'
      Contents: '**'
      TargetFolder: '$(Build.StagingDirectory)\\VS15'

  - task: CopyFiles@2
    displayName: Copy nupkgs to staging directory
    inputs:
      SourceFolder: '$(Build.Repository.LocalPath)\\artifacts\\$(NupkgOutputDir)'
      Contents: '**'
      TargetFolder: '$(Build.StagingDirectory)\\nupkgs'

    # Use dotnet msbuild instead of MSBuild CLI.
    # Using MSBuild CLI results in an assembly binding failure for NuGet.Common.dll 4.4.0.3 because Microsoft.DotNet.Build.Tasks.Feed.dll references SleetLib.dll which references NuGet.Common 4.4.0.3.
    # The Microsoft.DotNet.Build.Tasks.Feed package includes NuGet.Common 4.9.0.6 and a binding redirection in Microsoft.DotNet.Build.Tasks.Feed.dll.config but the binding redirection is not processed.
    # This would probably solve it:  https://github.com/Microsoft/msbuild/issues/1309
  - task: UseDotNet@2
    displayName: "Install .NET 10.0.0 for BAR publishing"
    inputs:
      packageType: sdk
      version: 10.0.x
      includePreviewVersions: true
      installationPath: $(Agent.TempDirectory)/dotnet
      workingDirectory: $(Agent.TempDirectory)
    condition: "and(succeeded(),eq(variables['PublishArtifactsToDotNetBuildAssetRegistry'], 'true'), eq(variables['BuildRTM'], 'false'))"

  - task: AzureCLI@2
    displayName: "Publish to the .NET Core build asset registry (BAR)"
    inputs:
      azureSubscription: "Darc: Maestro Production"
      scriptType: ps
      scriptLocation: inlineScript
      inlineScript: |
        $(Agent.TempDirectory)/dotnet/dotnet msbuild $(Build.Repository.LocalPath)\build\publish.proj /t:PublishToBuildAssetRegistry /property:NuGetClientNupkgsDirectoryPath=$(Build.Repository.LocalPath)\artifacts\$(NupkgOutputDir) /property:BUILD_BUILDNUMBER=$(Build.BuildNumber) /property:BUILD_SOURCEBRANCH=$(SourceBranch) /property:BUILD_SOURCEVERSION=$(Build.SourceVersion) /property:BUILD_REPOSITORY_URI=$(Build.Repository.Uri) /property:BUILD_REPOSITORY_NAME=$(Build.Repository.Name) /property:ArtifactsLogDir=$(Build.Repository.LocalPath)\artifacts\manifests\ /binarylogger:$(Build.StagingDirectory)\binlog\21.PublishToBuildAssetRegistry.binlog /property:MaestroApiEndpoint=$(MaestroApiEndpoint)
      workingDirectory: cli
      failOnStderr: true
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_MULTILEVEL_LOOKUP: true
    condition: "and(succeeded(),eq(variables['PublishArtifactsToDotNetBuildAssetRegistry'], 'true'), eq(variables['BuildRTM'], 'false'))"
