parameters:
- name: isOfficialBuild
  type: boolean
  default: false
- name: RunOneLocBuild
  displayName: Run OneLocBuild
  type: boolean
  default: false
- name: RunBuildForPublishing
  displayName: Build bits for publishing
  type: boolean
  default: true
- name: SigningType
  displayName: Type of signing to use
  type: string
  values:
  - Real
  - Test

stages:
- stage: Initialize
  jobs:
  - job: GetSemanticVersion
    displayName: Get NuGet.Client semantic version
    timeoutInMinutes: 10
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
      os: windows
    steps:
    - template: /eng/pipelines/templates/Initialize_Build_SemanticVersion.yml@self

  - job: Initialize_Build
    dependsOn: GetSemanticVersion
    timeoutInMinutes: 10
    variables:
      SemanticVersion: $[dependencies.GetSemanticVersion.outputs['setsemanticversion.SemanticVersion']]
      BuildRevision: $[counter(format('{0}.{1}', variables['SemanticVersion'], variables['build.definitionname']), 1)]
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
      os: windows
    steps:
    - template: /eng/pipelines/templates/Initialize_Build.yml@self

- ${{ if eq(parameters.RunOneLocBuild, true) }}:
  - stage: RunOneLocBuild
    displayName: Run OneLocBuild
    jobs:
    - template: /eng/common/templates-official/job/onelocbuild.yml
      parameters:
        LclSource: lclFilesfromPackage
        ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/dev') }}:
          LclPackageId: 'LCL-JUNO-PROD-NuGetClient'
        ${{ else }}:
          LclPackageId: 'LCL-JUNO-PROD-NuGetClientRel'
        MirrorRepo: 'NuGet.Client'
        MirrorBranch: ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', '') }}
        GitHubOrg: 'NuGet'

- stage: Build_Insertable
  displayName: Build NuGet inserted into VS and .NET SDK
  dependsOn: Initialize
  jobs:
  - job: Build_NonRTM
    timeoutInMinutes: 170
    variables:
      BuildNumber: $[stageDependencies.Initialize.Initialize_Build.outputs['updatebuildnumber.BuildNumber']]
      FullVstsBuildNumber: $[stageDependencies.Initialize.Initialize_Build.outputs['updatebuildnumber.FullVstsBuildNumber']]
      VsTargetChannel: $[stageDependencies.Initialize.Initialize_Build.outputs['updatebuildnumber.VsTargetChannel']]
      VsTargetChannelForTests: $[stageDependencies.Initialize.Initialize_Build.outputs['updatebuildnumber.VsTargetChannelForTests']]
      VsTargetMajorVersion: $[stageDependencies.Initialize.Initialize_Build.outputs['updatebuildnumber.VsTargetMajorVersion']]
      isOfficialBuild: ${{ parameters.isOfficialBuild }}
      BuildRTM: "false"
      SemanticVersion: $[stageDependencies.Initialize.GetSemanticVersion.outputs['setsemanticversion.SemanticVersion']]
      RunSettingsDropName: 'RunSettings/$(System.TeamProject)/$(Build.Repository.Name)/$(SourceBranch)/$(Build.BuildId)'
      ProfilingInputsDropName: 'ProfilingInputs/$(System.TeamProject)/$(Build.Repository.Name)/$(SourceBranch)/$(Build.BuildId)'
    pool:
      name: VSEngSS-MicroBuild2022-1ES
    templateContext:
      mb:
        localization:
          enabled: true
        signing:
          enabled: true
          signType: "${{ parameters.SigningType }}"
          ${{ if and(eq(parameters.isOfficialBuild, true), eq(parameters.SigningType, 'Real')) }}:
            signWithProd: true
        swix:
          enabled: true
        optprof:
          enabled: ${{ variables['isOfficialBuild'] }}
          OptimizationInputsLookupMethod: DropPrefix
          DropNamePrefix: OptimizationInputs/$(System.TeamProject)/$(Build.Repository.Name)
          ShouldSkipOptimize: $(ShouldSkipOptimize)
          AccessToken: $(System.AccessToken)
      outputParentDirectory: '$(Build.StagingDirectory)'
      outputs:
      - output: pipelineArtifact
        displayName: 'Publish buildinfo.json as an artifact'
        condition: "succeeded()"
        targetPath: '$(Build.StagingDirectory)\BuildInfo'
        artifactName: 'BuildInfo'
        sbomBuildDropPath: $(Build.SourcesDirectory)/artifacts

      - output: pipelineArtifact
        displayName: 'Publish nupkgs'
        targetPath: "$(Build.StagingDirectory)\\nupkgs"
        artifactName: "nupkgs - $(RtmLabel)"
        sbomBuildDropPath: $(Build.SourcesDirectory)/artifacts

      - output: artifactsDrop
        displayName: 'Publish the .runsettings files to artifact services'
        condition: "succeeded()"
        dropServiceURI: 'https://devdiv.artifacts.visualstudio.com'
        buildNumber: '$(RunSettingsDropName)'
        sourcePath: '$(Build.StagingDirectory)\RunSettings'
        toLowerCase: false
        usePat: true
        dropMetadataContainerName: 'DropMetadata-RunSettings'
        # need to make daily Apex test pipeline build its own tests, and remove this from official pipeline
        codeSignValidationEnabled: false

      - output: artifactsDrop
        displayName: 'OptProfV2:  publish profiling inputs to artifact services'
        condition: "and(succeeded(), eq(variables['IsOfficialBuild'], 'true'))"
        dropServiceURI: 'https://devdiv.artifacts.visualstudio.com'
        buildNumber: '$(ProfilingInputsDropName)'
        sourcePath: '$(Build.StagingDirectory)\OptProf\ProfilingInputs'
        toLowerCase: false
        usePat: true
        dropMetadataContainerName: 'DropMetadata-ProfilingInputs'

      - output: pipelineArtifact
        displayName: 'Publish NuGet.exe and VSIX as artifact'
        targetPath: "$(Build.StagingDirectory)\\VS15"
        artifactName: "$(VsixPublishDir)"
        sbomBuildDropPath: $(Build.SourcesDirectory)/artifacts

      - output: pipelineArtifact
        displayName: 'Publish symbols as pipeline artifacts'
        targetPath: "$(Build.StagingDirectory)\\symbolstoindex"
        artifactName: "symbols - $(RtmLabel)"
        sbomBuildDropPath: $(Build.SourcesDirectory)/artifacts

      - output: artifactsDrop
        displayName: 'Upload VSTS Drop'
        condition: "succeeded()"
        dropServiceURI: 'https://devdiv.artifacts.visualstudio.com'
        buildNumber: '$(MicroBuild.ManifestDropName)'
        sourcePath: "$(Build.StagingDirectory)\\VS15"
        toLowerCase: false
        usePat: true
        dropMetadataContainerName: "DropMetadata-Product"

      - output: pipelineArtifact
        displayName: 'LocValidation: Publish Logs as an artifact'
        condition: "succeededOrFailed()"
        artifactName: LocValidationLogs - Attempt $(System.JobAttempt)
        targetPath: "$(Build.StagingDirectory)\\BuildValidatorLogs"
        sbomEnabled: true

      - output: pipelineArtifact
        displayName: 'Publish binlogs'
        condition: "or(failed(), eq(variables['PublishArtifactsToDotNetBuildAssetRegistry'], 'true'), eq(variables['System.debug'], 'true'))"
        artifactName: binlog - $(System.JobDisplayName) - Attempt $(System.JobAttempt)
        targetPath: '$(Build.StagingDirectory)\binlog'
        sbomEnabled: false

      - output: pipelineArtifact
        displayName: Publish SBOM manifest
        artifactName: $(ARTIFACT_NAME)
        targetPath: "$(Build.StagingDirectory)/sbom"
        sbomEnabled: false

    steps:
    - template: /eng/pipelines/templates/Build.yml@self
      parameters:
        BuildRTM: false
        SigningType: ${{ parameters.SigningType }}

- stage: Build_For_Publishing
  displayName: Build NuGet published to nuget.org
  dependsOn: Initialize
  jobs:
  - job: Build_RTM
    condition: "and(succeeded(), ne(variables['RunBuildForPublishing'], 'false'))"
    timeoutInMinutes: 170
    variables:
      BuildNumber: $[stageDependencies.Initialize.Initialize_Build.outputs['updatebuildnumber.BuildNumber']]
      FullVstsBuildNumber: $[stageDependencies.Initialize.Initialize_Build.outputs['updatebuildnumber.FullVstsBuildNumber']]
      VsTargetChannel: $[stageDependencies.Initialize.Initialize_Build.outputs['updatebuildnumber.VsTargetChannel']]
      VsTargetChannelForTests: $[stageDependencies.Initialize.Initialize_Build.outputs['updatebuildnumber.VsTargetChannelForTests']]
      VsTargetMajorVersion: $[stageDependencies.Initialize.Initialize_Build.outputs['updatebuildnumber.VsTargetMajorVersion']]
      BuildRTM: "true"
    pool:
      name: VSEngSS-MicroBuild2022-1ES
    templateContext:
      mb:
        localization:
          enabled: true
        signing:
          enabled: true
          signType: "${{ parameters.SigningType }}"
          ${{ if and(eq(parameters.isOfficialBuild, true), eq(parameters.SigningType, 'Real')) }}:
            signWithProd: true
        swix:
          enabled: true
        optprof:
          enabled: false
      outputParentDirectory: '$(Build.StagingDirectory)'
      outputs:
      - output: pipelineArtifact
        displayName: 'Publish nupkgs'
        condition: "succeeded()"
        targetPath: "$(Build.StagingDirectory)\\$(NupkgOutputDir)"
        artifactName: "nupkgs - $(RtmLabel)"
        sbomBuildDropPath: $(Build.SourcesDirectory)/artifacts

      - output: pipelineArtifact
        displayName: 'Publish NuGet.exe and VSIX as artifact'
        targetPath: "$(Build.StagingDirectory)\\VS15"
        artifactName: "$(VsixPublishDir)"
        sbomBuildDropPath: $(Build.SourcesDirectory)/artifacts

      - output: pipelineArtifact
        displayName: 'Publish symbols as pipeline artifacts'
        targetPath: "$(Build.StagingDirectory)\\symbolstoindex"
        artifactName: "symbols - $(RtmLabel)"
        sbomBuildDropPath: $(Build.SourcesDirectory)/artifacts

      - output: pipelineArtifact
        displayName: 'Publish binlogs'
        condition: "or(failed(), eq(variables['PublishArtifactsToDotNetBuildAssetRegistry'], 'true'), eq(variables['System.debug'], 'true'))"
        artifactName: binlog - $(System.JobDisplayName) - Attempt $(System.JobAttempt)
        targetPath: $(Build.StagingDirectory)\binlog
        sbomBuildDropPath: $(Build.SourcesDirectory)/artifacts
    steps:
    - template: /eng/pipelines/templates/Build.yml@self
      parameters:
        BuildRTM: true
        SigningType: ${{ parameters.SigningType }}

  - job: Validate_Publishing_Artifacts
    condition: "and(succeeded(), ne(variables['RunBuildForPublishing'], 'false'))"
    displayName: 'Validate Publishing build artifacts'
    dependsOn: Build_RTM
    timeoutInMinutes: 15
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
      os: windows
    steps:
    - template: /eng/pipelines/templates/Validate_Build_Output.yml@self
      parameters:
        isOfficialBuild: ${{ parameters.isOfficialBuild }}
