parameters:
- name: EnableMacOSBuild
  type: boolean
- name: EnableLinuxBuild
  type: boolean

steps:
- download: current
  artifact: coverageResults-Windows
  displayName: 🔻 Download Windows code coverage results
  continueOnError: true
- ${{ if parameters.EnableLinuxBuild }}:
  - download: current
    artifact: coverageResults-Linux
    displayName: 🔻 Download Linux code coverage results
    continueOnError: true
- ${{ if parameters.EnableMacOSBuild }}:
  - download: current
    artifact: coverageResults-macOS
    displayName: 🔻 Download macOS code coverage results
    continueOnError: true
- powershell: azure-pipelines/Merge-CodeCoverage.ps1 -Path '$(Pipeline.Workspace)' -OutputFile coveragereport/merged.cobertura.xml -Format Cobertura -Verbose
  displayName: ⚙ Merge coverage
- task: PublishCodeCoverageResults@2
  displayName: 📢 Publish code coverage results to Azure DevOps
  inputs:
    summaryFileLocation: coveragereport/merged.cobertura.xml
    failIfCoverageEmpty: true
