steps:
- download: CI
  artifact: Variables-Windows
  displayName: 🔻 Download Variables-Windows artifact
- powershell: $(Pipeline.Workspace)/CI/Variables-Windows/_pipelines.ps1
  displayName: ⚙️ Set pipeline variables based on artifacts
