parameters:
  - name: dependsOn
    type: object
  - name: bootstrapperUrl
    type: string
  - name: runSettingsURI
    type: string
  - name: VsBootstrapperBranch
    type: string
  - name: condition
    type: string
  - name: variables
    type: object
  - name: testExecutionJobTimeoutInMinutes
    type: number
  - name: testDeploymentCleanupMode
    type: string
    default: OnSuccess
    values:
      - Always
      - Never
      - OnSuccess

stages:
  - template: stages/cloudtest/visual-studio/single-runsettings.yml@DartLabTemplates
    parameters:
      name: VS_Apex_Tests
      displayName: Apex Tests On Windows
      condition: ${{parameters.condition}}
      dependsOn: ${{parameters.dependsOn}}
      variables:
        - ${{if gt(length(parameters.variables), 0)}}:
          - ${{parameters.variables}}
      owner: nugetclienteng
      testMachineLab: "NuGet"
      runSettingsURI: ${{parameters.runSettingsURI}}
      visualStudioBootstrapperURI: ${{parameters.bootstrapperUrl}}
      visualStudioSigning: Test
      testMachineConfigurationJobTimeoutInMinutes: 30
      testMachineConfigurationJobDisplayName: 'Apex Test Machine Configuration'
      testExecutionJobDisplayName: 'Apex Test Execution'
      testExecutionJobTimeoutInMinutes: ${{parameters.testExecutionJobTimeoutInMinutes}}
      testDeploymentCleanupMode: ${{parameters.testDeploymentCleanupMode}}
      testMachineConfigurationJobVariables:
      - name: VisualStudio.InstallationUnderTest.BootstrapperBranch
        value: ${{parameters.VsBootstrapperBranch}}

##############################
## preDeployAndRunTestsOperations
##############################
      preDeployAndRunTestsOperations:
        - operation: executePowerShellInline
          displayName: "Print Environment Variables"
          scriptBlock: |
            Get-ChildItem Env: | Sort-Object Name | Format-Table -Wrap -AutoSize
          timeout: "0:0:5:0"

        - operation: downloadAzureArtifactsDrop
          displayName: "Download scripts"
          dropName: "$(RunSettingsDrop)"
          destinationDirectory: "c:\\nuget\\RunSettings"
          timeout: "0:0:10:0"

        - operation: executePowerShellScript
          displayName: "SetupFunctionalTests.ps1"
          scriptPath: "c:\\nuget\\RunSettings\\scripts\\e2etests\\SetupFunctionalTests.ps1"
          timeout: "0:0:10:0"
