parameters:
  engCommonTemplatesDir: ''

stages:
- stage: build
  displayName: Build
  jobs:
  - template: ${{ parameters.engCommonTemplatesDir }}/jobs/jobs.yml
    parameters:
      artifacts:
        publish:
          artifacts: true
          logs: true
      enablePublishTestResults: true
      enableTelemetry: true
      isAssetlessBuild: true
      publishAssetsImmediately: true

      jobs:
      - job: linux
        displayName: Linux
        pool:
          ${{ if eq(variables['System.TeamProject'], 'public') }}:
            name: $(DncEngPublicBuildPool)
            demands: ImageOverride -equals build.azurelinux.3.amd64.open
          ${{ if eq(variables['System.TeamProject'], 'internal') }}:
            name: $(DncEngInternalBuildPool)
            image: build.azurelinux.3.amd64
            os: linux
        container: mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net11.0-build-amd64
        variables:
        - _BuildConfig: Release
        steps:
        - checkout: self
          clean: true
          submodules: recursive
        - script: ./build.sh --ci --test -bl -c Release
          displayName: Build and Test

      - job: windows
        displayName: Windows
        pool:
          ${{ if eq(variables['System.TeamProject'], 'public') }}:
            name: $(DncEngPublicBuildPool)
            demands: ImageOverride -equals 1es-windows-2022-open
          ${{ if eq(variables['System.TeamProject'], 'internal') }}:
            name: $(DncEngInternalBuildPool)
            image: 1es-windows-2022
            os: windows
        variables:
        - _BuildConfig: Release
        steps:
        - script: git config --global core.longpaths true
          displayName: Enable long paths
        - checkout: self
          clean: true
          submodules: recursive
        - script: .\build.cmd -ci -test -bl -configuration Release
          displayName: Build and Test
