variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages/
  # #codecov_token: # Get a new one from https://codecov.io/
