trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
  paths:
    exclude:
    - '*.md'

pr:
  branches:
    include:
    - main
    - release/*
  paths:
    exclude:
    - '*.md'

variables:
  - template: /eng/common/templates/variables/pool-providers.yml
  - name: Codeql.Enable
    value: true

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      jobs:
      - job: SourceBuild_Managed
        displayName: Source-Build (Managed)
        pool:
          name: $(DncEngPublicBuildPool)
          demands: ImageOverride -equals Build.Ubuntu.2204.Amd64.Open
        container: 'mcr.microsoft.com/dotnet-buildtools/prereqs:centos-stream8'
        workspace:
          clean: all
        variables:
        - name: _BuildConfig
          value: Release
        steps:
        - checkout: self
          submodules: recursive
        - template: /eng/common/templates/steps/source-build.yml
