trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
  paths:
    exclude:
    - '*.md'
pr:
  branches:
    include:
    - main
    - release/*
  paths:
    exclude:
    - '*.md'
variables:
- template: /eng/common/templates-official/variables/pool-providers.yml
- name: TeamName
  value: DotNetSourceBuild
- name: Codeql.Enable
  value: true
resources:
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release
extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    sdl:
      binskim:
        enabled: true
      credscan:
        suppressionsFile: $(Build.SourcesDirectory)/.config/CredScanSuppressions.json
      policheck:
        enabled: true
      sourceAnalysisPool:
        name: $(DncEngInternalBuildPool)
        image: 1es-windows-2022
        os: windows
      tsa:
        enabled: true
    stages:
    - stage: build
      displayName: Build
      jobs:
      - template: /eng/common/templates-official/jobs/jobs.yml@self
        parameters:
          enablePublishUsingPipelines: true
          enablePublishBuildAssets: true
          artifacts:
            publish:
              artifacts: true
              manifests: true
          jobs:
          - job: SourceBuild_Managed
            displayName: Source-Build (Managed)
            pool:
              name: $(DncEngInternalBuildPool)
              image: 1es-ubuntu-2204
              os: linux
            container: 'mcr.microsoft.com/dotnet-buildtools/prereqs:centos-stream8'
            workspace:
              clean: all
            variables:
            - name: _BuildConfig
              value: Release
            steps:
            - checkout: self
              submodules: recursive
            - template: /eng/common/templates-official/steps/source-build.yml
    - ${{ if notin(variables['Build.Reason'], 'PullRequest') }}:
      - template: /eng/common/templates-official/post-build/post-build.yml@self
        parameters:
          publishingInfraVersion: 3
          enableSourceLinkValidation: true
          enableSigningValidation: false
