pool:
  name: VSEngSS-MicroBuild2022-1ES
  demands: msbuild

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: ''
  Codeql.Enabled: true

steps:
- task: MicroBuildSigningPlugin@1
  inputs:
    signType: '$(SignType)'
    zipSources: true

- task: MSBuild@1
  displayName: '/t:Pack'
  inputs:
    solution: MSBuildLocator.sln
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '/t:Pack /restore -binaryLogger:$(Build.SourcesDirectory)\Pack.binlog'

- task: CopyFiles@2
  displayName: 'Collect Symbols'
  inputs:
    SourceFolder: src/MSBuildLocator
    Contents: '**\*.pdb'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/symbols'
    CleanTargetFolder: true

- task: PublishSymbols@2
  displayName: 'Enable Source Server'
  inputs:
    SymbolsFolder: '$(Build.ArtifactStagingDirectory)\symbols'
    SearchPattern: '**/*.pdb'
    SymbolServerType: TeamServices

- task: PublishBuildArtifacts@1
  displayName: 'Upload Symbols Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/symbols'
    ArtifactName: Symbols

- task: CopyFiles@2
  displayName: 'Copy Bin to drop'
  inputs:
    SourceFolder: 'src\MSBuildLocator\bin\Release'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\bin'

- task: PublishBuildArtifacts@1
  displayName: 'Upload Bin to drop'
  inputs:
    PathToPublish: '$(Build.ArtifactStagingDirectory)\bin'
    ArtifactName: bin

- task: CopyFiles@2
  displayName: 'Copy NuGet to drop'
  inputs:
    SourceFolder: 'src\MSBuildLocator\bin\Release'
    Contents: '*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\pkg'

- task: PublishBuildArtifacts@1
  displayName: 'Upload NuGet to drop'
  inputs:
    PathToPublish: '$(Build.ArtifactStagingDirectory)\pkg'
    ArtifactName: pkg

- task: PublishPipelineArtifact@1
  displayName: 'Upload MicroBuildOutputs to drop'
  inputs:
    TargetPath: '$(Build.StagingDirectory)\MicroBuild\Output'
    ArtifactName: MicroBuildOutputs
  continueOnError: true

- task: CopyFiles@2
  displayName: 'Copy logs to drop'
  inputs:
    Contents: '**\*.*log'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\logs'

- task: PublishBuildArtifacts@1
  displayName: 'Upload logs to drop'
  inputs:
    PathToPublish: '$(Build.ArtifactStagingDirectory)\logs'
    ArtifactName: logs
  condition: succeededOrFailed()

- task: ms-vseng.MicroBuildTasks.521a94ea-9e68-468a-8167-6dcf361ea776.MicroBuildCleanup@1
  displayName: 'Execute cleanup tasks'
