trigger:
  - main
  - release/*

variables:
- name: BuildPlatform
  value: ''
- name: BuildConfiguration
  value: 'Release'
- name: TeamName
  value: 'MSBuildLocator'

resources:
  repositories:
  - repository: CustomPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@CustomPipelineTemplates
  parameters:
    pool:
      name: VSEngSS-MicroBuild2022-1ES
      demands:
      - msbuild
    sdl:
      sourceAnalysisPool:
        name: VSEngSS-MicroBuild2022-1ES
      policheck:
        enabled: true
      tsa:
        enabled: true
    stages:
    - stage: stage
      jobs:
      - job: job
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: 'Upload Symbols Artifact'
            targetPath: '$(Build.ArtifactStagingDirectory)/symbols'
            artifactName: Symbols
          - output: pipelineArtifact
            displayName: 'Upload Bin to drop'
            targetPath: '$(Build.ArtifactStagingDirectory)\bin'
            artifactName: bin
          - output: pipelineArtifact
            displayName: 'Upload NuGet to drop'
            targetPath: '$(Build.ArtifactStagingDirectory)\pkg'
            artifactName: pkg
          - output: pipelineArtifact
            displayName: 'Upload MicroBuildOutputs to drop'
            targetPath: '$(Build.StagingDirectory)\MicroBuild\Output'
            artifactName: MicroBuildOutputs
            continueOnError: true
          - output: pipelineArtifact
            displayName: 'Upload logs to drop'
            targetPath: '$(Build.ArtifactStagingDirectory)\logs'
            artifactName: logs
            condition: succeededOrFailed()
        steps:
        - task: MicroBuildSigningPlugin@1
          inputs:
            signType: '$(SignType)'
            zipSources: true

        - task: MSBuild@1
          displayName: '/t:Pack'
          inputs:
            solution: MSBuildLocator.sln
            platform: '$(BuildPlatform)'
            configuration: '$(BuildConfiguration)'
            msbuildArguments: '/t:Pack /restore -binaryLogger:$(Build.SourcesDirectory)\Pack.binlog'

        - task: CopyFiles@2
          displayName: 'Collect Symbols'
          inputs:
            SourceFolder: src/MSBuildLocator
            Contents: '**\*.pdb'
            TargetFolder: '$(Build.ArtifactStagingDirectory)\symbols'
            CleanTargetFolder: true

        - task: PublishSymbols@2
          displayName: 'Enable Source Server'
          inputs:
            SymbolsFolder: '$(Build.ArtifactStagingDirectory)\symbols'
            SearchPattern: '**/*.pdb'
            SymbolServerType: TeamServices

        - task: CopyFiles@2
          displayName: 'Copy Bin to drop'
          inputs:
            SourceFolder: 'src\MSBuildLocator\bin\Release'
            TargetFolder: '$(Build.ArtifactStagingDirectory)\bin'

        - task: CopyFiles@2
          displayName: 'Copy NuGet to drop'
          inputs:
            SourceFolder: 'src\MSBuildLocator\bin\Release'
            Contents: '*.nupkg'
            TargetFolder: '$(Build.ArtifactStagingDirectory)\pkg'

        - task: CopyFiles@2
          displayName: 'Copy logs to drop'
          inputs:
            Contents: '**\*.*log'
            TargetFolder: '$(Build.ArtifactStagingDirectory)\logs'

        - task: ms-vseng.MicroBuildTasks.521a94ea-9e68-468a-8167-6dcf361ea776.MicroBuildCleanup@1
          displayName: 'Execute cleanup tasks'