// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
// ------------------------------------------------------------------------------
// Changes to this file must follow the http://aka.ms/api-review process.
// ------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.ComTypes;
using System.Security;

[assembly: Debuggable(DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: AllowPartiallyTrustedCallers]
[assembly: ReferenceAssembly]
[assembly: AssemblyTitle("System.Runtime.InteropServices")]
[assembly: AssemblyDescription("System.Runtime.InteropServices")]
[assembly: AssemblyDefaultAlias("System.Runtime.InteropServices")]
[assembly: AssemblyCompany("Microsoft Corporation")]
[assembly: AssemblyProduct("Microsoft® .NET Framework")]
[assembly: AssemblyCopyright("© Microsoft Corporation.  All rights reserved.")]
[assembly: AssemblyFileVersion("1.0.24212.01")]
[assembly: AssemblyInformationalVersion("1.0.24212.01 built by: SOURCEBUILD")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyMetadata("", "")]
[assembly: AssemblyVersion("4.1.0.0")]

[assembly: TypeForwardedTo(typeof(System.DataMisalignedException))]
[assembly: TypeForwardedTo(typeof(System.DllNotFoundException))]
[assembly: TypeForwardedTo(typeof(System.Reflection.Missing))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ArrayWithOffset))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.BestFitMappingAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.BStrWrapper))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.CallingConvention))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ClassInterfaceAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ClassInterfaceType))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.CoClassAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComAwareEventInfo))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComDefaultInterfaceAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComEventInterfaceAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComEventsHelper))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.COMException))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComImportAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComInterfaceType))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComMemberType))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComSourceInterfacesAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.ADVF))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.BIND_OPTS))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.BINDPTR))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.CALLCONV))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.CONNECTDATA))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.DATADIR))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.DESCKIND))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.DISPPARAMS))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.DVASPECT))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.ELEMDESC))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.EXCEPINFO))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.FILETIME))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.FORMATETC))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.FUNCDESC))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.FUNCFLAGS))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.FUNCKIND))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.IAdviseSink))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.IBindCtx))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.IConnectionPoint))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.IConnectionPointContainer))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.IDLDESC))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.IDLFLAG))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.IEnumConnectionPoints))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.IEnumConnections))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.IEnumFORMATETC))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.IEnumMoniker))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.IEnumString))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.IEnumVARIANT))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.IMoniker))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.IMPLTYPEFLAGS))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.INVOKEKIND))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.IPersistFile))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.IRunningObjectTable))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.IStream))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.ITypeComp))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.ITypeInfo))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.ITypeInfo2))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.ITypeLib))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.ITypeLib2))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.LIBFLAGS))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.PARAMDESC))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.PARAMFLAG))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.STATDATA))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.STATSTG))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.STGMEDIUM))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.SYSKIND))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.TYMED))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.TYPEATTR))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.TYPEDESC))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.TYPEFLAGS))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.TYPEKIND))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.TYPELIBATTR))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.VARDESC))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.VARFLAGS))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.VARKIND))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.CriticalHandle))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.CurrencyWrapper))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.CustomQueryInterfaceMode))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.CustomQueryInterfaceResult))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.DefaultCharSetAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.DefaultDllImportSearchPathsAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.DefaultParameterValueAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.DispatchWrapper))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.DispIdAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.DllImportAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.DllImportSearchPath))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ErrorWrapper))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.GCHandle))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.GCHandleType))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.GuidAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.HandleCollector))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ICustomAdapter))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ICustomQueryInterface))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.InAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.InterfaceTypeAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.InvalidComObjectException))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.InvalidOleVariantTypeException))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.Marshal))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.MarshalAsAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.MarshalDirectiveException))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.OptionalAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.PreserveSigAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.SafeArrayRankMismatchException))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.SafeArrayTypeMismatchException))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.SafeBuffer))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.SafeHandle))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.SEHException))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.TypeIdentifierAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.UnknownWrapper))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.UnmanagedFunctionPointerAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.UnmanagedType))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.VarEnum))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.VariantWrapper))]



