// <auto-generated />
#pragma warning disable

#if !NET9_0_OR_GREATER

namespace System.Diagnostics;

using Diagnostics;
using Diagnostics.CodeAnalysis;

/// <summary>
/// If a .NET Debugger is attached that supports the <see cref="Debugger.BreakForUserUnhandledException(System.Exception)" /> API, the debugger won't break on user-unhandled exceptions when the exception is caught by a method with this attribute, unless <see cref="Debugger.BreakForUserUnhandledException(System.Exception)" /> is called.
/// </summary>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
[AttributeUsage(System.AttributeTargets.Method)]
//Link: https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debuggerdisableuserunhandledexceptionsattribute
#if PolyPublic
public
#endif
sealed class DebuggerDisableUserUnhandledExceptionsAttribute :
    Attribute;
#endif