// <auto-generated />
#pragma warning disable

#if (NETFRAMEWORK || NETSTANDARD2_0)

#nullable enable

namespace System.Collections.Generic;

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
// Provides the Create factory method for KeyValuePair<TKey, TValue>.
// https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.keyvaluepair
#if PolyPublic
public
#endif
static class KeyValuePair
{
    /// <summary>
    /// Creates a new key/value pair instance using provided values.
    /// </summary>
    /// <param name="key">The key of the new <see cref="KeyValuePair{TKey,TValue}"/> to be created.</param>
    /// <param name="value">The value of the new <see cref="KeyValuePair{TKey,TValue}"/> to be created.</param>
    /// <typeparam name="TKey">The type of the key.</typeparam>
    /// <typeparam name="TValue">The type of the value.</typeparam>
    /// <returns>A key/value pair containing the provided arguments as values.</returns>
    //Link: https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.keyvaluepair.create
    public static KeyValuePair<TKey, TValue> Create<TKey, TValue>(TKey key, TValue value) =>
        new KeyValuePair<TKey, TValue>(key, value);
}
#endif
