// <auto-generated />
#pragma warning disable

#if !NET9_0_OR_GREATER

namespace System.Runtime.CompilerServices;

using Diagnostics;
using Diagnostics.CodeAnalysis;

/// <summary>
/// Indicates that a method allows a variable number of arguments in its invocation.
/// </summary>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
[AttributeUsage(AttributeTargets.Parameter, Inherited = true, AllowMultiple = false)]
//Link: https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.paramcollectionattribute
#if PolyPublic
public
#endif
sealed class ParamCollectionAttribute : Attribute;

#endif