// <auto-generated />
#pragma warning disable

#if NETFRAMEWORK || NETSTANDARD2_0

namespace Polyfills;

using System;
using System.Collections.Concurrent;

static partial class Polyfill
{
    /// <summary>
    /// Removes all values from the <see cref="ConcurrentQueue{T}"/>.
    /// </summary>
    //Link: https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentqueue-1.clear
    public static void Clear<T>(this ConcurrentQueue<T> target)
    {
        while (target.TryDequeue(out _));
    }
}
#endif