// <auto-generated />

using System.Runtime.CompilerServices;

#pragma warning disable

namespace Polyfills;

using System;
using System.Collections.Concurrent;

static partial class Polyfill
{
    /// <summary>
    /// Gets a value that indicates whether the Delegate has a single invocation target.
    /// </summary>
    //Link: https://learn.microsoft.com/en-us/dotnet/api/system.delegate.hassingletarget
    public static bool HasSingleTarget(this Delegate target)
    {
#if NET9_0_OR_GREATER
        return target.HasSingleTarget;
#else
        return target.GetInvocationList().Length == 1;
#endif
    }
}
