# This yml is used by these pipelines:
# - dotnet-unified-build (internal)
#   https://dev.azure.com/dnceng/internal/_build?definitionId=1330

trigger:
  batch: true
  branches:
    include:
      - main
      - release/*
      - internal/release/*

schedules:
  - cron: "0 12 * * 0,6" # run every Saturday and Sunday at 12:00 (UTC)
    displayName: Signed main build on weekends
    branches:
      include:
      - main
    always: true

parameters:
- name: desiredSigning
  displayName: 'Sign?'
  type: string
  default: 'Default (unsigned for non release-branch builds)'
  values:
    - Signed (Real)
    - Signed (Test)
    - Signed (Dry Run)
    - Unsigned
    - Default (unsigned for non release-branch builds)

- name: desiredIBC
  displayName: 'Enable IBC?'
  type: string
  default: 'Default (disabled for non-release branch builds)'
  values:
    - Enabled
    - Disabled
    - Default (disabled for non-release branch builds)

- name: desiredFinalVersionKind
  displayName: 'Final version kind'
  type: string
  default: 'Default (repo specifies)'
  values:
    - Default (repo specifies)
    - Stable Preview
    - Stable Final

variables:
- name: isScheduleTrigger
  value: ${{ eq(variables['Build.Reason'], 'Schedule') }}

- ${{ if eq(variables['System.TeamProject'], 'public') }}:
  - name: skipComponentGovernanceDetection  # we run CG on internal builds only
    value: true

  - name: Codeql.Enabled  # we run CodeQL on internal builds only
    value: false

- template: /eng/common/templates-official/variables/pool-providers.yml@self
- template: /eng/pipelines/templates/variables/vmr-build.yml@self

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    featureFlags:
      incrementalSDLBinaryAnalysis: true
      autoEnableRoslynWithNewRuleset: false
    sdl:
      sourceAnalysisPool:
        name: $(DncEngInternalBuildPool)
        image: 1es-windows-2022
        os: windows

      # Spotbugs is failing the Windows builds: https://github.com/dotnet/dnceng/issues/2740
      spotBugs:
        enabled: false

      codeql:
        compiled:
          enabled: true
        # Runs analysis in the SDL stage and not every job
        # https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/sdlanalysis/codeql#improving-codeql-performance
        runSourceLanguagesInSourceAnalysis: true
        tsaEnabled: true
      binskim:
        enabled: true
        # This may need to be updated to exclude files we don't want scanned.
        # This pattern was pulled from dotnet/sdk, with the ESRPClient added.
        # When binskim supports scanning of archive contents, this can be removed altogether.
        # This is of the form: <pattern>;<pattern>
        # +:f| - Include glob
        # -:f| - Exclude glob
        analyzeTargetGlob: +:f|eng\**\*.props;+:f|**\artifacts\bin\**\*.dll;+:f|**\artifacts\bin\**\*.exe;-:f|**\artifacts\bin\**\msdia140.dll;-:f|**\artifacts\bin\**\pgort140.dll;-:f|**\artifacts\bin\*Tests\**;-:f|**\Microsoft.NET.Runtime.Emscripten**\tools\**;-:f|**\CodeCoverage\**;-:f|**\artifacts\bin\**\capstone.dll;-:f|**\Microsoft.EsrpClient\**;-:f|**\artifacts\bin\**\SuperFileCheck\**\llvm-mca.exe;-:f|**\artifacts\bin\**\SuperFileCheck\**\FileCheck.exe;
      policheck:
        enabled: true
      tsa:
        enabled: true

    containers:
      ${{ variables.almaLinuxContainerName }}:
        image: ${{ variables.almaLinuxContainerImage }}
        options: ${{ variables.defaultContainerOptions }}
      ${{ variables.alpineContainerName }}:
        image: ${{ variables.alpineContainerImage }}
        options: ${{ variables.defaultContainerOptions }}
      ${{ variables.centOSStreamContainerName }}:
        image: ${{ variables.centOSStreamContainerImage }}
        options: ${{ variables.defaultContainerOptions }}
      ${{ variables.fedoraContainerName }}:
        image: ${{ variables.fedoraContainerImage }}
        options: ${{ variables.defaultContainerOptions }}
      ${{ variables.ubuntuContainerName }}:
        image: ${{ variables.ubuntuContainerImage }}
        options: ${{ variables.defaultContainerOptions }}
      ${{ variables.ubuntuArmContainerName }}:
        image: ${{ variables.ubuntuArmContainerImage }}
        options: ${{ variables.defaultContainerOptions }}
      ${{ variables.azurelinuxX64CrossContainerName }}:
        image: ${{ variables.azurelinuxX64CrossContainerImage }}
        options: ${{ variables.defaultContainerOptions }}
      ${{ variables.azurelinuxArmCrossContainerName }}:
        image: ${{ variables.azurelinuxArmCrossContainerImage }}
        options: ${{ variables.defaultContainerOptions }}
      ${{ variables.azurelinuxArm64CrossContainerName }}:
        image: ${{ variables.azurelinuxArm64CrossContainerImage }}
        options: ${{ variables.defaultContainerOptions }}
      ${{ variables.azurelinuxX64MuslCrossContainerName }}:
        image: ${{ variables.azurelinuxX64MuslCrossContainerImage }}
        options: ${{ variables.defaultContainerOptions }}
      ${{ variables.azurelinuxArmMuslCrossContainerName }}:
        image: ${{ variables.azurelinuxArmMuslCrossContainerImage }}
        options: ${{ variables.defaultContainerOptions }}
      ${{ variables.azurelinuxArm64MuslCrossContainerName }}:
        image: ${{ variables.azurelinuxArm64MuslCrossContainerImage }}
        options: ${{ variables.defaultContainerOptions }}
      ${{ variables.androidCrossContainerName }}:
        image: ${{ variables.androidCrossContainerImage }}
        options: ${{ variables.defaultContainerOptions }}
      ${{ variables.linuxBionicCrossContainerName }}:
        image: ${{ variables.linuxBionicCrossContainerImage }}
        options: ${{ variables.defaultContainerOptions }}
      ${{ variables.browserCrossContainerName }}:
        image: ${{ variables.browserCrossContainerImage }}
        options: ${{ variables.defaultContainerOptions }}
      ${{ variables.wasiCrossContainerName }}:
        image: ${{ variables.wasiCrossContainerImage }}
        options: ${{ variables.defaultContainerOptions }}

    stages:
    - template: /eng/pipelines/templates/stages/vmr-scan.yml@self
    - template: /eng/pipelines/templates/stages/vmr-build.yml@self
      parameters:
        ${{ if and(eq(variables.isScheduleTrigger, 'true'), eq(variables['Build.CronSchedule.DisplayName'], 'Signed main build on weekends')) }}:
          desiredSigning: Signed (Real)
        ${{ else }}:
          desiredSigning: ${{ parameters.desiredSigning }}
        desiredIBC: ${{ parameters.desiredIBC }}
        desiredFinalVersionKind: ${{ parameters.desiredFinalVersionKind }}
        isOfficialBuild: true
        scope: full
