# This yml is used by these pipelines and triggers:
# - dotnet-unified-build (public)
# - dotnet-unified-build-full (public)

# Only run daily on schedule to save resources
trigger: none

pr:
  branches:
    include:
    - main
    - release/*

schedules:
  - cron: "0 1 * * *" # run at 01:00 (UTC)
    branches:
      include:
      - main
    always: false # run only if there were changes since the last successful scheduled run.

variables:
# enable source-only build for pipelines that contain the -source-build string
- name: isSourceOnlyBuild
  value: ${{ contains(variables['Build.DefinitionName'], '-source-build') }}

- name: isSourceOnlyBuildLite
  value: ${{ contains(variables['Build.DefinitionName'], '-source-build-lite') }}

- name: isScheduleTrigger
  value: ${{ eq(variables['Build.Reason'], 'Schedule') }}

- name: isPRTrigger
  value: ${{ eq(variables['Build.Reason'], 'PullRequest') }}

- ${{ if eq(variables['System.TeamProject'], 'public') }}:
  - name: skipComponentGovernanceDetection  # we run CG on internal builds only
    value: true

  - name: Codeql.Enabled  # we run CodeQL on internal builds only
    value: false

- template: /eng/common/templates/variables/pool-providers.yml@self

stages:
- template: /eng/pipelines/templates/stages/vmr-build.yml
  parameters:
    isSourceOnlyBuild: ${{ variables.isSourceOnlyBuild }}
    ${{ if or(eq(variables.isScheduleTrigger, 'true'), contains(variables['Build.DefinitionName'], '-full')) }}:
      scope: full
    ${{ elseif eq(variables.isSourceOnlyBuildLite, 'true') }}:
      scope: lite
    ${{ elseif and(eq(variables.isPRTrigger, 'true'), eq(variables.isSourceOnlyBuild, 'true')) }}:
      scope: ultralite
    ${{ elseif and(eq(variables.isPRTrigger, 'true'), ne(variables.isSourceOnlyBuild, 'true')) }}:
      scope: lite
    ${{ else }}:
      scope: full
