# This yml is used by these PR pipelines and triggers:
# NOTE: the triggers are defined in the Azure DevOps UI as they are too complex
#
# - dotnet-unified-build (public)
#   https://dev.azure.com/dnceng-public/public/_build?definitionId=278
#   - PR: lite build
#   - CI: release/* only, every batched commit, full build
#   - Schedule: main only, full build
#
# - dotnet-unified-build-full (public)
#   https://dev.azure.com/dnceng-public/public/_build?definitionId=303
#   Comment trigger only

variables:
- name: isScheduleTrigger
  value: ${{ eq(variables['Build.Reason'], 'Schedule') }}

- name: isPRTrigger
  value: ${{ eq(variables['Build.Reason'], 'PullRequest') }}

- ${{ if eq(variables['System.TeamProject'], 'public') }}:
  - name: skipComponentGovernanceDetection  # we run CG on internal builds only
    value: true

  - name: Codeql.Enabled  # we run CodeQL on internal builds only
    value: false

- template: /eng/common/templates/variables/pool-providers.yml@self

stages:
- template: /eng/pipelines/templates/stages/vmr-build.yml
  parameters:
    ${{ if or(eq(variables.isScheduleTrigger, 'true'), contains(variables['Build.DefinitionName'], '-full')) }}:
      scope: full
    ${{ elseif eq(variables.isPRTrigger, 'true') }}:
      scope: lite
    ${{ else }}:
      scope: full
