# This yml is used by these pipelines:
# - dotnet-unified-build (public)
#   https://dev.azure.com/dnceng-public/public/_build?definitionId=278
# - dotnet-unified-build-full (public)
#   https://dev.azure.com/dnceng-public/public/_build?definitionId=303
#   Comment trigger only

# Only run daily on schedule to save resources
trigger: none

pr:
  branches:
    include:
    - main
    - release/*

schedules:
  - cron: "0 1 * * *" # run at 01:00 (UTC)
    branches:
      include:
      - main
    always: false # run only if there were changes since the last successful scheduled run.

variables:
- name: isScheduleTrigger
  value: ${{ eq(variables['Build.Reason'], 'Schedule') }}

- name: isPRTrigger
  value: ${{ eq(variables['Build.Reason'], 'PullRequest') }}

- ${{ if eq(variables['System.TeamProject'], 'public') }}:
  - name: skipComponentGovernanceDetection  # we run CG on internal builds only
    value: true

  - name: Codeql.Enabled  # we run CodeQL on internal builds only
    value: false

- template: /eng/common/templates/variables/pool-providers.yml@self

stages:
- template: /eng/pipelines/templates/stages/vmr-build.yml
  parameters:
    ${{ if or(eq(variables.isScheduleTrigger, 'true'), contains(variables['Build.DefinitionName'], '-full')) }}:
      scope: full
    ${{ elseif eq(variables.isPRTrigger, 'true') }}:
      scope: lite
    ${{ else }}:
      scope: full

- stage: ValidateUserChanges
  displayName: Validate user changes in VMR
  dependsOn: []
  condition: and(
                eq(variables['isPRTrigger'], 'true'),
                and(
                    ne(variables['Build.RequestedForEmail'], 'maestro-dotnet-bot@microsoft.com'),
                    ne(variables['Build.RequestedForEmail'], 'dotnet-sb-bot@microsoft.com')
                    ) 
                )
  jobs:
  - job: Validate
    displayName: Run Validation Script
    pool:
      vmImage: windows-latest
    steps:
    - checkout: self
      fetchDepth: 0

    - powershell: |
        Write-Host "Fetching target branch: $(System.PullRequest.TargetBranch)"
        git fetch origin $(System.PullRequest.TargetBranch)

        . "$(Build.SourcesDirectory)\eng\common\tools.ps1"
        InitializeDotNetCli -install $true

        & "$env:DOTNET_INSTALL_DIR\dotnet.exe" run --project eng/tools/ChangeValidation/ChangeValidation.csproj
      displayName: Run ChangeValidation tool
      env:
        SYSTEM_PULLREQUEST_TARGETBRANCH: $(System.PullRequest.TargetBranch)
        SYSTEM_PULLREQUEST_SOURCEBRANCH: $(System.PullRequest.SourceBranch)
        SYSTEM_PULLREQUEST_PULLREQUESTNUMBER: $(System.PullRequest.PullRequestNumber)

