# This yml is used by these pipelines:
# - dotnet-unified-build (public)
#   https://dev.azure.com/dnceng-public/public/_build?definitionId=278
# - dotnet-unified-build-full (public)
#   https://dev.azure.com/dnceng-public/public/_build?definitionId=303
#   Comment trigger only

# Only run daily on schedule to save resources
trigger: none

pr:
  branches:
    include:
    - main
    - release/*

schedules:
  - cron: "0 14 * * *" # run at 14:00 (UTC)
    branches:
      include:
      - main
    always: false # run only if there were changes since the last successful scheduled run.

parameters:
- name: buildScope
  displayName: 'Build Scope'
  type: string
  default: 'auto'
  values:
    - auto
    - lite
    - full

variables:
- name: isScheduleTrigger
  value: ${{ eq(variables['Build.Reason'], 'Schedule') }}

- name: isPRTrigger
  value: ${{ eq(variables['Build.Reason'], 'PullRequest') }}

- ${{ if eq(variables['System.TeamProject'], 'public') }}:
  - name: skipComponentGovernanceDetection  # we run CG on internal builds only
    value: true

  - name: Codeql.Enabled  # we run CodeQL on internal builds only
    value: false

- template: /eng/common/templates/variables/pool-providers.yml@self

stages:
- template: /eng/pipelines/templates/stages/vmr-build.yml
  parameters:
    ${{ if eq(parameters.buildScope, 'auto') }}:
      ${{ if or(eq(variables.isScheduleTrigger, 'true'), contains(variables['Build.DefinitionName'], '-full')) }}:
        scope: full
      ${{ elseif eq(variables.isPRTrigger, 'true') }}:
        scope: lite
      ${{ else }}:
        scope: full
    ${{ else }}:
      scope: full
    # Exclude runtime dependent jobs for any branch not producing a 1xx version since runtime-related repos aren't built in that context
    # This is enabled for all branches except main and 1xx
    excludeRuntimeDependentJobs: false

- stage: ValidateUserChanges
  displayName: Validate user changes in VMR
  dependsOn: []
  condition: and(
              eq(variables['isPRTrigger'], 'true'),
              and(
                  not(startsWith(variables['System.PullRequest.SourceBranch'], 'refs/heads/darc-')),
                  not(startsWith(variables['System.PullRequest.SourceBranch'], 'darc-'))
              )
          )
  jobs:
    - job: Validate
      displayName: Run Validation Script
      pool:
        vmImage: windows-latest
      steps:
        - checkout: self
          fetchDepth: 0

        - powershell: |
            Write-Host "Fetching target branch: $(System.PullRequest.TargetBranch)"
            git fetch origin $(System.PullRequest.TargetBranch)
          displayName: Fetch target branch

        - powershell: |
            . "$(Build.SourcesDirectory)\eng\common\tools.ps1"
            InitializeDotNetCli -install $true
            Write-Host "##vso[task.setvariable variable=DOTNET_INSTALL_DIR]$env:DOTNET_INSTALL_DIR"
          displayName: Initialize .NET CLI

        - powershell: |
            & "$(DOTNET_INSTALL_DIR)\dotnet.exe" run --project eng/tools/ChangeValidation/ChangeValidation.csproj
          displayName: Run ChangeValidation tool
          env:
            SYSTEM_PULLREQUEST_TARGETBRANCH: $(System.PullRequest.TargetBranch)
            SYSTEM_PULLREQUEST_SOURCEBRANCH: $(System.PullRequest.SourceBranch)
            SYSTEM_PULLREQUEST_PULLREQUESTNUMBER: $(System.PullRequest.PullRequestNumber)
