# This yml is used by these pipelines:
# - dotnet-unified-build-scout (public)

# Only run 3 times a week on schedule to save resources
trigger: none

pr: none

schedules:
  - cron: "0 9 * * 0,2,4" # run 3 days a week at 9:00 (UTC)
    branches:
      include:
      - main
    always: true # run even if there are no new commits, in case the build images changed.
  - cron: "0 9 * * 1,3,5" # run 3 days a week at 9:00 (UTC)
    branches:
      include:
      - release/*
    always: false # only run on new commits for release/* branches, so as not to build stale branches.

variables:
- ${{ if eq(variables['System.TeamProject'], 'public') }}:
  - name: skipComponentGovernanceDetection  # we run CG on internal builds only
    value: true

  - name: Codeql.Enabled  # we run CodeQL on internal builds only
    value: false

- template: /eng/common/templates/variables/pool-providers.yml@self

stages:
- template: /eng/pipelines/templates/stages/vmr-build.yml
  parameters:
    scope: scout
