schedules:
- cron: "0 12 * * 1-5"
  displayName: Run on weekdays at 12pm UTC
  branches:
    include:
    - main

# Relies on dotnet-unified-build being in the same repo as this pipeline
# https://learn.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops#branch-considerations
resources:
  pipelines:
  - pipeline: dotnet-unified-build
    source: dotnet-unified-build
    # For releases branches only run on internal/release branches because that's where dependencies flow.
    # Previews don't have internal/release branches so they must be run from non-internal release branches.
    trigger:
      branches:
        include:
        - refs/heads/release/*.0.1xx-preview*
        - refs/heads/internal/release/*.0.1xx*
      # Trigger on build stages vs successful pipeline completion for a higher run frequency when there are
      # publish/validation failures.
      stages:
        - VMR_Vertical_Build
        - VMR_SourceOnly_Build

  - pipeline: dotnet-source-build-pre10.0
    source: dotnet-source-build-pre10.0
    # For releases branches only run on internal/release branches because that's where dependencies flow.
    # Previews don't have internal/release branches so they must be run from non-internal release branches.
    trigger:
      branches:
        include:
        - refs/heads/release/*.0.1xx-preview*
        - refs/heads/internal/release/*.0.1xx*

  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

pr: none
trigger: none

parameters:
- name: dotnetDotnetRunId
  displayName: 'Specific dotnet-dotnet run ID number (e.g `2108850`)'
  type: string
  default: ' '

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: NetCore1ESPool-Svc-Internal
      image: 1es-ubuntu-2204
      os: linux
    sdl:
      sourceAnalysisPool:
          name: NetCore1ESPool-Svc-Internal
          image: 1es-windows-2022
          os: windows
      binskim:
        enabled: true
      policheck:
        enabled: true
      tsa:
        enabled: true
    stages:
    - template: /eng/pipelines/templates/stages/source-build-sdk-diff-tests.yml@self
      parameters:
        dotnetDotnetRunId: ${{ parameters.dotnetDotnetRunId }}
