schedules:
- cron: "0 11 * * 1-5"
  displayName: Run on weekdays at 11am UTC
  branches:
    include:
    - main

# Relies on dotnet-source-build being in the same repo as this pipeline
# https://learn.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops#branch-considerations
resources:
  pipelines:
  - pipeline: dotnet-source-build-pre10.0
    source: dotnet-source-build-pre10.0
    trigger:
      branches:
        include:
          - release/*.0.1xx*
          - internal/release/*.0.1xx*

  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

pr: none
trigger: none

parameters:
- name: dotnetDotnetRunId
  displayName: 'Specific dotnet-dotnet run ID number (e.g `2108850`)'
  type: string
  default: ' '

variables:
- template: /src/installer/eng/pipelines/templates/variables/vmr-build.yml@self

# GH access token for SB bot - BotAccount-dotnet-sb-bot-pat
- group: Dotnet-SourceBuild-Secrets

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: NetCore1ESPool-Svc-Internal
      image: 1es-ubuntu-2204
      os: linux
    sdl:
      sourceAnalysisPool:
        name: NetCore1ESPool-Svc-Internal
        image: 1es-windows-2022
        os: windows
    stages:
    - stage: stage
      jobs:
      - template: /eng/pipelines/templates/jobs/sdk-diff-tests.yml@self
        parameters:
          buildName: ${{ format('{0}_Offline_MsftSdk', variables.centOSStreamName) }}
          targetRid: ${{ variables.centOSStreamX64Rid }}
          architecture: x64
          dotnetDotnetRunId: ${{ parameters.dotnetDotnetRunId }}
          publishTestResultsPr: true

      - template: /eng/pipelines/templates/jobs/sdk-diff-tests.yml@self
        parameters:
          buildName: ${{ format('{0}_Offline_MsftSdk', variables.almaLinuxName) }}
          targetRid: ${{ variables.almaLinuxX64Rid }}
          architecture: x64
          dotnetDotnetRunId: ${{ parameters.dotnetDotnetRunId }}

      - template: /eng/pipelines/templates/jobs/sdk-diff-tests.yml@self
        parameters:
          buildName: ${{ format('{0}_Offline_MsftSdk', variables.alpineName) }}
          targetRid: ${{ variables.alpineX64Rid }}
          architecture: x64
          dotnetDotnetRunId: ${{ parameters.dotnetDotnetRunId }}

      - template: /eng/pipelines/templates/jobs/sdk-diff-tests.yml@self
        parameters:
          buildName: ${{ format('{0}_Offline_MsftSdk', variables.fedoraName) }}
          targetRid: ${{ variables.fedoraX64Rid }}
          architecture: x64
          dotnetDotnetRunId: ${{ parameters.dotnetDotnetRunId }}

      - template: /eng/pipelines/templates/jobs/sdk-diff-tests.yml@self
        parameters:
          buildName: ${{ format('{0}_Offline_MsftSdk', variables.ubuntuName) }}
          targetRid: ${{ variables.ubuntuX64Rid }}
          architecture: x64
          dotnetDotnetRunId: ${{ parameters.dotnetDotnetRunId }}

      - template: /eng/pipelines/templates/jobs/sdk-diff-tests.yml@self
        parameters:
          buildName: ${{ format('{0}Arm64_Offline_MsftSdk', variables.ubuntuName) }}
          targetRid: ${{ variables.ubuntuArm64Rid }}
          architecture: arm64
          dotnetDotnetRunId: ${{ parameters.dotnetDotnetRunId }}
