<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <arcadeGitCommitHash>f3bffca1f93573c88a7f9b79fac258dff76f6215</arcadeGitCommitHash>
    <arcadeOutputPackageVersion>9.0.0-beta.26406.11</arcadeOutputPackageVersion>
    <aspireGitCommitHash>5fa9337a84a52e9bd185d04d156eccbdcf592f74</aspireGitCommitHash>
    <aspireOutputPackageVersion>8.2.2-preview.1.24521.5</aspireOutputPackageVersion>
    <aspnetcoreGitCommitHash>4e6235b8f9af12335ecd58a0a06b8f4105af2de0</aspnetcoreGitCommitHash>
    <aspnetcoreOutputPackageVersion>9.0.20-servicing.26414.7</aspnetcoreOutputPackageVersion>
    <cecilGitCommitHash>eebca361032c2a1ded7be6244b91b757d54be02a</cecilGitCommitHash>
    <cecilOutputPackageVersion>0.11.5-alpha.26404.3</cecilOutputPackageVersion>
    <commandlineapiGitCommitHash>803d8598f98fb4efd94604b32627ee9407f246db</commandlineapiGitCommitHash>
    <commandlineapiOutputPackageVersion>0.1.532403</commandlineapiOutputPackageVersion>
    <deploymenttoolsGitCommitHash>b2d5c0c5841de4bc036ef4c84b5db3532504e5f3</deploymenttoolsGitCommitHash>
    <deploymenttoolsOutputPackageVersion>9.0.0-rtm.25059.4</deploymenttoolsOutputPackageVersion>
    <diagnosticsGitCommitHash>513150c2f25077b1fcb194407e53c433c975f39b</diagnosticsGitCommitHash>
    <diagnosticsOutputPackageVersion>8.0.0-preview.24416.1</diagnosticsOutputPackageVersion>
    <efcoreGitCommitHash>e3050de15c005dfd3223da1475572044b72a6758</efcoreGitCommitHash>
    <efcoreOutputPackageVersion>9.0.20</efcoreOutputPackageVersion>
    <emsdkGitCommitHash>b2bf6cec0cb4ce281802ac3951bdd14287aad112</emsdkGitCommitHash>
    <emsdkOutputPackageVersion>9.0.20-servicing.26406.7</emsdkOutputPackageVersion>
    <fsharpGitCommitHash>47d4e3f91e4e5414b6dafbf14288b9c5a798ef99</fsharpGitCommitHash>
    <fsharpOutputPackageVersion>9.0.101-beta.25070.7</fsharpOutputPackageVersion>
    <msbuildGitCommitHash>07da1b9a89da6d00c5a5a6a385cdcebfdfed7110</msbuildGitCommitHash>
    <msbuildOutputPackageVersion>17.12.57-preview-26069-01</msbuildOutputPackageVersion>
    <nugetclientGitCommitHash>c92125011405028c945371a89e1a1eb0e735456d</nugetclientGitCommitHash>
    <nugetclientOutputPackageVersion>6.12.5-rc.1</nugetclientOutputPackageVersion>
    <razorGitCommitHash>cff92f3cc3f19a607ddbb7a0cddfbccf87a1c061</razorGitCommitHash>
    <razorOutputPackageVersion>9.0.0-preview.26069.1</razorOutputPackageVersion>
    <roslynanalyzersGitCommitHash>b9b54526b7908ea519b503196100a34dd2e52374</roslynanalyzersGitCommitHash>
    <roslynanalyzersOutputPackageVersion>3.11.0-beta1.26226.5</roslynanalyzersOutputPackageVersion>
    <roslynGitCommitHash>fc52718eccdb37693a40a518b1178b1e23114e68</roslynGitCommitHash>
    <roslynOutputPackageVersion>4.12.0-3.25609.5</roslynOutputPackageVersion>
    <runtimeGitCommitHash>3879076d9a06ce098d37c3882fb1845a6627335b</runtimeGitCommitHash>
    <runtimeOutputPackageVersion>9.0.20-servicing.26413.15</runtimeOutputPackageVersion>
    <scenariotestsGitCommitHash>83d50199a618f84d9cb5d442dcc70c46023d1108</scenariotestsGitCommitHash>
    <scenariotestsOutputPackageVersion>9.0.0-preview.26407.1</scenariotestsOutputPackageVersion>
    <sdkGitCommitHash>09bf54e912f2c0efa6f10e35fa9dd5c4051fb16b</sdkGitCommitHash>
    <sourcebuildassetsGitCommitHash>9693cbc172a06845f5b8799bdf098c055d728166</sourcebuildassetsGitCommitHash>
    <sourcebuildassetsOutputPackageVersion>9.0.0-alpha.1.26405.2</sourcebuildassetsOutputPackageVersion>
    <sourcebuildexternalsGitCommitHash>1c800169e674c7becf88434a0d2817453cf91dd7</sourcebuildexternalsGitCommitHash>
    <sourcebuildexternalsOutputPackageVersion>9.0.0-alpha.1.26366.1</sourcebuildexternalsOutputPackageVersion>
    <sourcebuildreferencepackagesGitCommitHash>fe3794a68bd668d36d4d5014a9e6c9d22c0e6d86</sourcebuildreferencepackagesGitCommitHash>
    <sourcebuildreferencepackagesOutputPackageVersion>8.0.0-alpha.1.24415.1</sourcebuildreferencepackagesOutputPackageVersion>
    <sourcelinkGitCommitHash>1e7bb033fe99a4a968e44c38e64e903dd58a5430</sourcelinkGitCommitHash>
    <sourcelinkOutputPackageVersion>9.0.0-beta.26351.3</sourcelinkOutputPackageVersion>
    <symreaderGitCommitHash>0710a7892d89999956e8808c28e9dd0512bd53f3</symreaderGitCommitHash>
    <symreaderOutputPackageVersion>2.2.0-beta.24327.2</symreaderOutputPackageVersion>
    <templatingGitCommitHash>d6bb682832461366b9fe50dee7a72c7feeadbc41</templatingGitCommitHash>
    <templatingOutputPackageVersion>9.0.121-servicing.26412.3</templatingOutputPackageVersion>
    <testtemplatesGitCommitHash>47c90e140b027225b799ca8413af10ee3d5f1126</testtemplatesGitCommitHash>
    <testtemplatesOutputPackageVersion>1.1.0-rtm.25262.1</testtemplatesOutputPackageVersion>
    <vstestGitCommitHash>bc9161306b23641b0364b8f93d546da4d48da1eb</vstestGitCommitHash>
    <vstestOutputPackageVersion>17.12.0-release-24508-01</vstestOutputPackageVersion>
    <windowsdesktopGitCommitHash>daf3521d2c06f60c6549079094c391732bc59d15</windowsdesktopGitCommitHash>
    <windowsdesktopOutputPackageVersion>9.0.20</windowsdesktopOutputPackageVersion>
    <winformsGitCommitHash>6502cec45fb6ee15a78a39105e6cd9ccf2e6c364</winformsGitCommitHash>
    <winformsOutputPackageVersion>9.0.20-servicing.26414.2</winformsOutputPackageVersion>
    <wpfGitCommitHash>f32f0c216455878a8eabe2caf23ad5cba55d3d0a</wpfGitCommitHash>
    <wpfOutputPackageVersion>9.0.20-rtm.26414.3</wpfOutputPackageVersion>
    <xdtGitCommitHash>63ae81154c50a1cf9287cc47d8351d55b4289e6d</xdtGitCommitHash>
    <xdtOutputPackageVersion>10.0.0-preview.24609.2</xdtOutputPackageVersion>
    <xlifftasksGitCommitHash>73f0850939d96131c28cf6ea6ee5aacb4da0083a</xlifftasksGitCommitHash>
    <xlifftasksOutputPackageVersion>1.0.0-beta.23475.1</xlifftasksOutputPackageVersion>
  </PropertyGroup>
</Project>