<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>a249c754b0f0ac7f313f659343fe24a4a73d573a</GitCommitHash>
    <OfficialBuildId>20260804.5</OfficialBuildId>
    <OutputPackageVersion>9.0.0-beta.26404.5</OutputPackageVersion>
    <PreReleaseVersionLabel>beta</PreReleaseVersionLabel>
    <IsStable>false</IsStable>
  </PropertyGroup>
</Project>