<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>0992a0f871c48ccc32eaa49ad89fea8022b8f597</GitCommitHash>
    <OfficialBuildId>20260810.9</OfficialBuildId>
    <OutputPackageVersion>8.0.0-beta.26410.9</OutputPackageVersion>
    <PreReleaseVersionLabel>beta</PreReleaseVersionLabel>
    <IsStable>false</IsStable>
  </PropertyGroup>
</Project>