<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>db19187bf519d94ddafe8300748e52bba023df1d</GitCommitHash>
    <OfficialBuildId>20260813.29</OfficialBuildId>
    <OutputPackageVersion>8.0.31-servicing.26413.29</OutputPackageVersion>
    <PreReleaseVersionLabel>servicing</PreReleaseVersionLabel>
    <IsStable>false</IsStable>
  </PropertyGroup>
</Project>