<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>d98c55d1363411ee1a0ff0c76c6e5d798e8147ec</GitCommitHash>
    <OfficialBuildId>20260703.2</OfficialBuildId>
    <OutputPackageVersion>0.11.5-alpha.26353.2</OutputPackageVersion>
    <PreReleaseVersionLabel>alpha</PreReleaseVersionLabel>
    <IsStable>false</IsStable>
  </PropertyGroup>
</Project>