<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>a1cb4f641df8967b3338e6f630f594ca4962b467</GitCommitHash>
    <OfficialBuildId>20260729.1</OfficialBuildId>
    <OutputPackageVersion>0.11.4-alpha.26379.1</OutputPackageVersion>
    <PreReleaseVersionLabel>alpha</PreReleaseVersionLabel>
    <IsStable>false</IsStable>
  </PropertyGroup>
</Project>