<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>b2bf6cec0cb4ce281802ac3951bdd14287aad112</GitCommitHash>
    <OfficialBuildId>20260806.7</OfficialBuildId>
    <OutputPackageVersion>9.0.20-servicing.26406.7</OutputPackageVersion>
    <PreReleaseVersionLabel>servicing</PreReleaseVersionLabel>
    <IsStable>false</IsStable>
  </PropertyGroup>
</Project>