<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>d04ebc5885458432cac9626ef5a2851ac51f94e9</GitCommitHash>
    <OfficialBuildId>20260729.1</OfficialBuildId>
    <OutputPackageVersion>8.0.100</OutputPackageVersion>
    <PreReleaseVersionLabel></PreReleaseVersionLabel>
    <IsStable>true</IsStable>
  </PropertyGroup>
</Project>