<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>e71ae12a90a6dfb9a39f3ede894602a329386d89</GitCommitHash>
    <OfficialBuildId>20260910.1</OfficialBuildId>
    <OutputPackageVersion>8.0.100</OutputPackageVersion>
    <PreReleaseVersionLabel></PreReleaseVersionLabel>
    <IsStable>true</IsStable>
  </PropertyGroup>
</Project>