<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>2a6130a2996d5cd81b39e1f05a7736b0685fc870</GitCommitHash>
    <OfficialBuildId>20260925.3</OfficialBuildId>
    <OutputPackageVersion>17.12.77-preview-26475-03</OutputPackageVersion>
    <PreReleaseVersionLabel>preview</PreReleaseVersionLabel>
    <IsStable>false</IsStable>
  </PropertyGroup>
</Project>