<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>1219a42122cf5190c7f512850557e38c422430dc</GitCommitHash>
    <OfficialBuildId>20260820.15</OfficialBuildId>
    <OutputPackageVersion>8.0.31-servicing.26420.15</OutputPackageVersion>
    <PreReleaseVersionLabel>servicing</PreReleaseVersionLabel>
    <IsStable>false</IsStable>
  </PropertyGroup>
</Project>