<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>2a19dd15d054021e9cb1d97fe3ceb6df910e4bcc</GitCommitHash>
    <OfficialBuildId>20260813.7</OfficialBuildId>
    <OutputPackageVersion>8.0.31-servicing.26413.7</OutputPackageVersion>
    <PreReleaseVersionLabel>servicing</PreReleaseVersionLabel>
    <IsStable>false</IsStable>
  </PropertyGroup>
</Project>