<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>a83db3e0eb2defb6220e15dae2f1a0462fdbf99f</GitCommitHash>
    <OfficialBuildId>20260717.20</OfficialBuildId>
    <OutputPackageVersion>8.0.30-servicing.26367.20</OutputPackageVersion>
    <PreReleaseVersionLabel>servicing</PreReleaseVersionLabel>
    <IsStable>false</IsStable>
  </PropertyGroup>
</Project>