<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>83d50199a618f84d9cb5d442dcc70c46023d1108</GitCommitHash>
    <OfficialBuildId>20260807.1</OfficialBuildId>
    <OutputPackageVersion>9.0.0-preview.26407.1</OutputPackageVersion>
    <PreReleaseVersionLabel>preview</PreReleaseVersionLabel>
    <IsStable>false</IsStable>
  </PropertyGroup>
</Project>