<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>35ad058513d080958eb4534859b8977e3d6234ff</GitCommitHash>
    <OfficialBuildId>20260806.2</OfficialBuildId>
    <OutputPackageVersion>9.0.0-preview.26406.2</OutputPackageVersion>
    <PreReleaseVersionLabel>preview</PreReleaseVersionLabel>
    <IsStable>false</IsStable>
  </PropertyGroup>
</Project>