<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>715f87326e6080d0ff38e209fc44fe89eadc52bd</GitCommitHash>
    <OfficialBuildId>20260814.4</OfficialBuildId>
    <OutputPackageVersion>8.0.131-servicing.26414.4</OutputPackageVersion>
    <PreReleaseVersionLabel>servicing</PreReleaseVersionLabel>
    <IsStable>false</IsStable>
  </PropertyGroup>
</Project>