<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>b7cb81089af89db111181f2b7e0d4de9fc4da1ef</GitCommitHash>
    <OfficialBuildId>20260815.1</OfficialBuildId>
    <OutputPackageVersion>0.0.0</OutputPackageVersion>
    <PreReleaseVersionLabel></PreReleaseVersionLabel>
    <IsStable>true</IsStable>
  </PropertyGroup>
</Project>