<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>eccb0828682858d8daa029ba29adce07fd70d9a7</GitCommitHash>
    <OfficialBuildId>20260901.2</OfficialBuildId>
    <OutputPackageVersion>9.0.0-alpha.1.26451.2</OutputPackageVersion>
    <PreReleaseVersionLabel>alpha.1</PreReleaseVersionLabel>
    <IsStable>false</IsStable>
  </PropertyGroup>
</Project>