<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>490113ea252cb25880a7abc9926af8ffcf471e33</GitCommitHash>
    <OfficialBuildId>20261001.1</OfficialBuildId>
    <OutputPackageVersion>8.0.0-alpha.1.26501.1</OutputPackageVersion>
    <PreReleaseVersionLabel>alpha.1</PreReleaseVersionLabel>
    <IsStable>false</IsStable>
  </PropertyGroup>
</Project>