<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>5aeee2738338530a92d7f6caa2c7d5f569fed3c4</GitCommitHash>
    <OfficialBuildId>20261001.1</OfficialBuildId>
    <OutputPackageVersion>8.0.0-alpha.1.26501.1</OutputPackageVersion>
    <PreReleaseVersionLabel>alpha.1</PreReleaseVersionLabel>
    <IsStable>false</IsStable>
  </PropertyGroup>
</Project>