<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>d6bb682832461366b9fe50dee7a72c7feeadbc41</GitCommitHash>
    <OfficialBuildId>20260812.3</OfficialBuildId>
    <OutputPackageVersion>9.0.121-servicing.26412.3</OutputPackageVersion>
    <PreReleaseVersionLabel>servicing</PreReleaseVersionLabel>
    <IsStable>false</IsStable>
  </PropertyGroup>
</Project>