<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>5e02510389b93426cd94b5d2bbb10c9205d0bdbb</GitCommitHash>
    <OfficialBuildId>20260727.6</OfficialBuildId>
    <OutputPackageVersion>9.0.120-servicing.26377.6</OutputPackageVersion>
    <PreReleaseVersionLabel>servicing</PreReleaseVersionLabel>
    <IsStable>false</IsStable>
  </PropertyGroup>
</Project>