<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>4a2048b77c7de671b08320e346c73da6fd6d9aeb</GitCommitHash>
    <OfficialBuildId>20260818.1</OfficialBuildId>
    <OutputPackageVersion>9.0.19</OutputPackageVersion>
    <PreReleaseVersionLabel></PreReleaseVersionLabel>
    <IsStable>true</IsStable>
  </PropertyGroup>
</Project>