<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>daf3521d2c06f60c6549079094c391732bc59d15</GitCommitHash>
    <OfficialBuildId>20260815.1</OfficialBuildId>
    <OutputPackageVersion>9.0.20</OutputPackageVersion>
    <PreReleaseVersionLabel></PreReleaseVersionLabel>
    <IsStable>true</IsStable>
  </PropertyGroup>
</Project>