<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>f32f0c216455878a8eabe2caf23ad5cba55d3d0a</GitCommitHash>
    <OfficialBuildId>20260814.3</OfficialBuildId>
    <OutputPackageVersion>9.0.20-rtm.26414.3</OutputPackageVersion>
    <PreReleaseVersionLabel>rtm</PreReleaseVersionLabel>
    <IsStable>false</IsStable>
  </PropertyGroup>
</Project>