<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>b11f25ba2d9d291ca38621d7ba15ad9563e96d30</GitCommitHash>
    <OfficialBuildId>20260821.6</OfficialBuildId>
    <OutputPackageVersion>9.0.20-rtm.26421.6</OutputPackageVersion>
    <PreReleaseVersionLabel>rtm</PreReleaseVersionLabel>
    <IsStable>false</IsStable>
  </PropertyGroup>
</Project>