// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
// ------------------------------------------------------------------------------
// Changes to this file must follow the http://aka.ms/api-review process.
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Reflection;
using System.Runtime;
using System.Runtime.CompilerServices;
using System.Runtime.ExceptionServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
using System.Security;
using System.Text;
using System.Threading;

[assembly: Debuggable(DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: AllowPartiallyTrustedCallers]
[assembly: ReferenceAssembly]
[assembly: AssemblyTitle("System.Runtime")]
[assembly: AssemblyDescription("System.Runtime")]
[assembly: AssemblyDefaultAlias("System.Runtime")]
[assembly: AssemblyCompany("Microsoft Corporation")]
[assembly: AssemblyProduct("Microsoft® .NET Framework")]
[assembly: AssemblyCopyright("© Microsoft Corporation.  All rights reserved.")]
[assembly: AssemblyFileVersion("1.0.24212.01")]
[assembly: AssemblyInformationalVersion("1.0.24212.01 built by: SOURCEBUILD")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyMetadata("", "")]
[assembly: AssemblyVersion("4.1.0.0")]

[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.GCHandle))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.GCHandleType))]
[assembly: TypeForwardedTo(typeof(System.Action))]
[assembly: TypeForwardedTo(typeof(System.Action<>))]
[assembly: TypeForwardedTo(typeof(System.Action<, , , , , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Action<, , , , , , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Action<, , , , , , , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Action<, , , , , , , , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Action<, , , , , , , , , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Action<, , , , , , , , , , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Action<, , , , , , , , , , , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Action<, >))]
[assembly: TypeForwardedTo(typeof(System.Action<, , >))]
[assembly: TypeForwardedTo(typeof(System.Action<, , , >))]
[assembly: TypeForwardedTo(typeof(System.Action<, , , , >))]
[assembly: TypeForwardedTo(typeof(System.Action<, , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Action<, , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Action<, , , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Action<, , , , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Activator))]
[assembly: TypeForwardedTo(typeof(System.ArgumentException))]
[assembly: TypeForwardedTo(typeof(System.ArgumentNullException))]
[assembly: TypeForwardedTo(typeof(System.ArgumentOutOfRangeException))]
[assembly: TypeForwardedTo(typeof(System.ArithmeticException))]
[assembly: TypeForwardedTo(typeof(System.Array))]
[assembly: TypeForwardedTo(typeof(System.ArraySegment<>))]
[assembly: TypeForwardedTo(typeof(System.ArrayTypeMismatchException))]
[assembly: TypeForwardedTo(typeof(System.AsyncCallback))]
[assembly: TypeForwardedTo(typeof(System.Attribute))]
[assembly: TypeForwardedTo(typeof(System.AttributeTargets))]
[assembly: TypeForwardedTo(typeof(System.AttributeUsageAttribute))]
[assembly: TypeForwardedTo(typeof(System.BadImageFormatException))]
[assembly: TypeForwardedTo(typeof(System.Boolean))]
[assembly: TypeForwardedTo(typeof(System.Buffer))]
[assembly: TypeForwardedTo(typeof(System.Byte))]
[assembly: TypeForwardedTo(typeof(System.Char))]
[assembly: TypeForwardedTo(typeof(System.CLSCompliantAttribute))]
[assembly: TypeForwardedTo(typeof(System.Collections.DictionaryEntry))]
[assembly: TypeForwardedTo(typeof(System.Collections.Generic.ICollection<>))]
[assembly: TypeForwardedTo(typeof(System.Collections.Generic.IComparer<>))]
[assembly: TypeForwardedTo(typeof(System.Collections.Generic.IDictionary<, >))]
[assembly: TypeForwardedTo(typeof(System.Collections.Generic.IEnumerable<>))]
[assembly: TypeForwardedTo(typeof(System.Collections.Generic.IEnumerator<>))]
[assembly: TypeForwardedTo(typeof(System.Collections.Generic.IEqualityComparer<>))]
[assembly: TypeForwardedTo(typeof(System.Collections.Generic.IList<>))]
[assembly: TypeForwardedTo(typeof(System.Collections.Generic.IReadOnlyCollection<>))]
[assembly: TypeForwardedTo(typeof(System.Collections.Generic.IReadOnlyDictionary<, >))]
[assembly: TypeForwardedTo(typeof(System.Collections.Generic.IReadOnlyList<>))]
[assembly: TypeForwardedTo(typeof(System.Collections.Generic.ISet<>))]
[assembly: TypeForwardedTo(typeof(System.Collections.Generic.KeyNotFoundException))]
[assembly: TypeForwardedTo(typeof(System.Collections.Generic.KeyValuePair<, >))]
[assembly: TypeForwardedTo(typeof(System.Collections.ICollection))]
[assembly: TypeForwardedTo(typeof(System.Collections.IComparer))]
[assembly: TypeForwardedTo(typeof(System.Collections.IDictionary))]
[assembly: TypeForwardedTo(typeof(System.Collections.IDictionaryEnumerator))]
[assembly: TypeForwardedTo(typeof(System.Collections.IEnumerable))]
[assembly: TypeForwardedTo(typeof(System.Collections.IEnumerator))]
[assembly: TypeForwardedTo(typeof(System.Collections.IEqualityComparer))]
[assembly: TypeForwardedTo(typeof(System.Collections.IList))]
[assembly: TypeForwardedTo(typeof(System.Collections.IStructuralComparable))]
[assembly: TypeForwardedTo(typeof(System.Collections.IStructuralEquatable))]
[assembly: TypeForwardedTo(typeof(System.Collections.ObjectModel.Collection<>))]
[assembly: TypeForwardedTo(typeof(System.Collections.ObjectModel.ReadOnlyCollection<>))]
[assembly: TypeForwardedTo(typeof(System.Comparison<>))]
[assembly: TypeForwardedTo(typeof(System.ComponentModel.DefaultValueAttribute))]
[assembly: TypeForwardedTo(typeof(System.ComponentModel.EditorBrowsableAttribute))]
[assembly: TypeForwardedTo(typeof(System.ComponentModel.EditorBrowsableState))]
[assembly: TypeForwardedTo(typeof(System.DateTime))]
[assembly: TypeForwardedTo(typeof(System.DateTimeKind))]
[assembly: TypeForwardedTo(typeof(System.DateTimeOffset))]
[assembly: TypeForwardedTo(typeof(System.DayOfWeek))]
[assembly: TypeForwardedTo(typeof(System.Decimal))]
[assembly: TypeForwardedTo(typeof(System.Delegate))]
[assembly: TypeForwardedTo(typeof(System.Diagnostics.ConditionalAttribute))]
[assembly: TypeForwardedTo(typeof(System.Diagnostics.DebuggableAttribute))]
[assembly: TypeForwardedTo(typeof(System.DivideByZeroException))]
[assembly: TypeForwardedTo(typeof(System.Double))]
[assembly: TypeForwardedTo(typeof(System.Enum))]
[assembly: TypeForwardedTo(typeof(System.EventArgs))]
[assembly: TypeForwardedTo(typeof(System.EventHandler))]
[assembly: TypeForwardedTo(typeof(System.EventHandler<>))]
[assembly: TypeForwardedTo(typeof(System.Exception))]
[assembly: TypeForwardedTo(typeof(System.FieldAccessException))]
[assembly: TypeForwardedTo(typeof(System.FlagsAttribute))]
[assembly: TypeForwardedTo(typeof(System.FormatException))]
[assembly: TypeForwardedTo(typeof(System.FormattableString))]
[assembly: TypeForwardedTo(typeof(System.Func<>))]
[assembly: TypeForwardedTo(typeof(System.Func<, , , , , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Func<, , , , , , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Func<, , , , , , , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Func<, , , , , , , , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Func<, , , , , , , , , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Func<, , , , , , , , , , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Func<, , , , , , , , , , , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Func<, , , , , , , , , , , , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Func<, >))]
[assembly: TypeForwardedTo(typeof(System.Func<, , >))]
[assembly: TypeForwardedTo(typeof(System.Func<, , , >))]
[assembly: TypeForwardedTo(typeof(System.Func<, , , , >))]
[assembly: TypeForwardedTo(typeof(System.Func<, , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Func<, , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Func<, , , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Func<, , , , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.GC))]
[assembly: TypeForwardedTo(typeof(System.GCCollectionMode))]
[assembly: TypeForwardedTo(typeof(System.Globalization.DateTimeStyles))]
[assembly: TypeForwardedTo(typeof(System.Globalization.NumberStyles))]
[assembly: TypeForwardedTo(typeof(System.Globalization.TimeSpanStyles))]
[assembly: TypeForwardedTo(typeof(System.Guid))]
[assembly: TypeForwardedTo(typeof(System.IAsyncResult))]
[assembly: TypeForwardedTo(typeof(System.IComparable))]
[assembly: TypeForwardedTo(typeof(System.IComparable<>))]
[assembly: TypeForwardedTo(typeof(System.IConvertible))]
[assembly: TypeForwardedTo(typeof(System.ICustomFormatter))]
[assembly: TypeForwardedTo(typeof(System.IDisposable))]
[assembly: TypeForwardedTo(typeof(System.IEquatable<>))]
[assembly: TypeForwardedTo(typeof(System.IFormatProvider))]
[assembly: TypeForwardedTo(typeof(System.IFormattable))]
[assembly: TypeForwardedTo(typeof(System.IndexOutOfRangeException))]
[assembly: TypeForwardedTo(typeof(System.InsufficientExecutionStackException))]
[assembly: TypeForwardedTo(typeof(System.Int16))]
[assembly: TypeForwardedTo(typeof(System.Int32))]
[assembly: TypeForwardedTo(typeof(System.Int64))]
[assembly: TypeForwardedTo(typeof(System.IntPtr))]
[assembly: TypeForwardedTo(typeof(System.InvalidCastException))]
[assembly: TypeForwardedTo(typeof(System.InvalidOperationException))]
[assembly: TypeForwardedTo(typeof(System.InvalidProgramException))]
[assembly: TypeForwardedTo(typeof(System.InvalidTimeZoneException))]
[assembly: TypeForwardedTo(typeof(System.IO.DirectoryNotFoundException))]
[assembly: TypeForwardedTo(typeof(System.IO.FileLoadException))]
[assembly: TypeForwardedTo(typeof(System.IO.FileNotFoundException))]
[assembly: TypeForwardedTo(typeof(System.IO.IOException))]
[assembly: TypeForwardedTo(typeof(System.IO.PathTooLongException))]
[assembly: TypeForwardedTo(typeof(System.IObservable<>))]
[assembly: TypeForwardedTo(typeof(System.IObserver<>))]
[assembly: TypeForwardedTo(typeof(System.IProgress<>))]
[assembly: TypeForwardedTo(typeof(System.Lazy<>))]
[assembly: TypeForwardedTo(typeof(System.Lazy<, >))]
[assembly: TypeForwardedTo(typeof(System.MemberAccessException))]
[assembly: TypeForwardedTo(typeof(System.MethodAccessException))]
[assembly: TypeForwardedTo(typeof(System.MissingFieldException))]
[assembly: TypeForwardedTo(typeof(System.MissingMemberException))]
[assembly: TypeForwardedTo(typeof(System.MissingMethodException))]
[assembly: TypeForwardedTo(typeof(System.MTAThreadAttribute))]
[assembly: TypeForwardedTo(typeof(System.MulticastDelegate))]
[assembly: TypeForwardedTo(typeof(System.NotImplementedException))]
[assembly: TypeForwardedTo(typeof(System.NotSupportedException))]
[assembly: TypeForwardedTo(typeof(System.Nullable))]
[assembly: TypeForwardedTo(typeof(System.Nullable<>))]
[assembly: TypeForwardedTo(typeof(System.NullReferenceException))]
[assembly: TypeForwardedTo(typeof(System.Object))]
[assembly: TypeForwardedTo(typeof(System.ObjectDisposedException))]
[assembly: TypeForwardedTo(typeof(System.ObsoleteAttribute))]
[assembly: TypeForwardedTo(typeof(System.OutOfMemoryException))]
[assembly: TypeForwardedTo(typeof(System.OverflowException))]
[assembly: TypeForwardedTo(typeof(System.ParamArrayAttribute))]
[assembly: TypeForwardedTo(typeof(System.PlatformNotSupportedException))]
[assembly: TypeForwardedTo(typeof(System.Predicate<>))]
[assembly: TypeForwardedTo(typeof(System.RankException))]
[assembly: TypeForwardedTo(typeof(System.Reflection.AssemblyCompanyAttribute))]
[assembly: TypeForwardedTo(typeof(System.Reflection.AssemblyConfigurationAttribute))]
[assembly: TypeForwardedTo(typeof(System.Reflection.AssemblyCopyrightAttribute))]
[assembly: TypeForwardedTo(typeof(System.Reflection.AssemblyCultureAttribute))]
[assembly: TypeForwardedTo(typeof(System.Reflection.AssemblyDefaultAliasAttribute))]
[assembly: TypeForwardedTo(typeof(System.Reflection.AssemblyDelaySignAttribute))]
[assembly: TypeForwardedTo(typeof(System.Reflection.AssemblyDescriptionAttribute))]
[assembly: TypeForwardedTo(typeof(System.Reflection.AssemblyFileVersionAttribute))]
[assembly: TypeForwardedTo(typeof(System.Reflection.AssemblyFlagsAttribute))]
[assembly: TypeForwardedTo(typeof(System.Reflection.AssemblyInformationalVersionAttribute))]
[assembly: TypeForwardedTo(typeof(System.Reflection.AssemblyKeyFileAttribute))]
[assembly: TypeForwardedTo(typeof(System.Reflection.AssemblyKeyNameAttribute))]
[assembly: TypeForwardedTo(typeof(System.Reflection.AssemblyMetadataAttribute))]
[assembly: TypeForwardedTo(typeof(System.Reflection.AssemblyNameFlags))]
[assembly: TypeForwardedTo(typeof(System.Reflection.AssemblyProductAttribute))]
[assembly: TypeForwardedTo(typeof(System.Reflection.AssemblySignatureKeyAttribute))]
[assembly: TypeForwardedTo(typeof(System.Reflection.AssemblyTitleAttribute))]
[assembly: TypeForwardedTo(typeof(System.Reflection.AssemblyTrademarkAttribute))]
[assembly: TypeForwardedTo(typeof(System.Reflection.AssemblyVersionAttribute))]
[assembly: TypeForwardedTo(typeof(System.Reflection.DefaultMemberAttribute))]
[assembly: TypeForwardedTo(typeof(System.Reflection.ProcessorArchitecture))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.AccessedThroughPropertyAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.AsyncStateMachineAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.CallerFilePathAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.CallerLineNumberAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.CallerMemberNameAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.CompilationRelaxationsAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.CompilerGeneratedAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.ConditionalWeakTable<, >))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.CustomConstantAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.DateTimeConstantAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.DecimalConstantAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.DisablePrivateReflectionAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.ExtensionAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.FixedBufferAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.FormattableStringFactory))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.IndexerNameAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.InternalsVisibleToAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.IsConst))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.IStrongBox))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.IsVolatile))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.IteratorStateMachineAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.MethodImplAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.MethodImplOptions))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.ReferenceAssemblyAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.RuntimeCompatibilityAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.RuntimeHelpers))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.StateMachineAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.StrongBox<>))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.TypeForwardedFromAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.TypeForwardedToAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.UnsafeValueTypeAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.ExceptionServices.ExceptionDispatchInfo))]
[assembly: TypeForwardedTo(typeof(System.Runtime.GCLargeObjectHeapCompactionMode))]
[assembly: TypeForwardedTo(typeof(System.Runtime.GCLatencyMode))]
[assembly: TypeForwardedTo(typeof(System.Runtime.GCSettings))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.CharSet))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComVisibleAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.FieldOffsetAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.LayoutKind))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.OutAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.StructLayoutAttribute))]
[assembly: TypeForwardedTo(typeof(System.Runtime.Versioning.TargetFrameworkAttribute))]
[assembly: TypeForwardedTo(typeof(System.RuntimeFieldHandle))]
[assembly: TypeForwardedTo(typeof(System.RuntimeMethodHandle))]
[assembly: TypeForwardedTo(typeof(System.RuntimeTypeHandle))]
[assembly: TypeForwardedTo(typeof(System.SByte))]
[assembly: TypeForwardedTo(typeof(System.Security.AllowPartiallyTrustedCallersAttribute))]
[assembly: TypeForwardedTo(typeof(System.Security.SecurityCriticalAttribute))]
[assembly: TypeForwardedTo(typeof(System.Security.SecurityException))]
[assembly: TypeForwardedTo(typeof(System.Security.SecuritySafeCriticalAttribute))]
[assembly: TypeForwardedTo(typeof(System.Security.SecurityTransparentAttribute))]
[assembly: TypeForwardedTo(typeof(System.Security.VerificationException))]
[assembly: TypeForwardedTo(typeof(System.Single))]
[assembly: TypeForwardedTo(typeof(System.STAThreadAttribute))]
[assembly: TypeForwardedTo(typeof(System.String))]
[assembly: TypeForwardedTo(typeof(System.StringComparison))]
[assembly: TypeForwardedTo(typeof(System.StringSplitOptions))]
[assembly: TypeForwardedTo(typeof(System.Text.StringBuilder))]
[assembly: TypeForwardedTo(typeof(System.Threading.LazyThreadSafetyMode))]
[assembly: TypeForwardedTo(typeof(System.Threading.Timeout))]
[assembly: TypeForwardedTo(typeof(System.Threading.WaitHandle))]
[assembly: TypeForwardedTo(typeof(System.ThreadStaticAttribute))]
[assembly: TypeForwardedTo(typeof(System.TimeoutException))]
[assembly: TypeForwardedTo(typeof(System.TimeSpan))]
[assembly: TypeForwardedTo(typeof(System.TimeZoneInfo))]
[assembly: TypeForwardedTo(typeof(System.Tuple))]
[assembly: TypeForwardedTo(typeof(System.Tuple<>))]
[assembly: TypeForwardedTo(typeof(System.Tuple<, >))]
[assembly: TypeForwardedTo(typeof(System.Tuple<, , >))]
[assembly: TypeForwardedTo(typeof(System.Tuple<, , , >))]
[assembly: TypeForwardedTo(typeof(System.Tuple<, , , , >))]
[assembly: TypeForwardedTo(typeof(System.Tuple<, , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Tuple<, , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Tuple<, , , , , , , >))]
[assembly: TypeForwardedTo(typeof(System.Type))]
[assembly: TypeForwardedTo(typeof(System.TypeAccessException))]
[assembly: TypeForwardedTo(typeof(System.TypeCode))]
[assembly: TypeForwardedTo(typeof(System.TypeInitializationException))]
[assembly: TypeForwardedTo(typeof(System.TypeLoadException))]
[assembly: TypeForwardedTo(typeof(System.UInt16))]
[assembly: TypeForwardedTo(typeof(System.UInt32))]
[assembly: TypeForwardedTo(typeof(System.UInt64))]
[assembly: TypeForwardedTo(typeof(System.UIntPtr))]
[assembly: TypeForwardedTo(typeof(System.UnauthorizedAccessException))]
[assembly: TypeForwardedTo(typeof(System.Uri))]
[assembly: TypeForwardedTo(typeof(System.UriComponents))]
[assembly: TypeForwardedTo(typeof(System.UriFormat))]
[assembly: TypeForwardedTo(typeof(System.UriFormatException))]
[assembly: TypeForwardedTo(typeof(System.UriHostNameType))]
[assembly: TypeForwardedTo(typeof(System.UriKind))]
[assembly: TypeForwardedTo(typeof(System.ValueType))]
[assembly: TypeForwardedTo(typeof(System.Version))]
[assembly: TypeForwardedTo(typeof(void))]
[assembly: TypeForwardedTo(typeof(System.WeakReference))]
[assembly: TypeForwardedTo(typeof(System.WeakReference<>))]



