// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
// ------------------------------------------------------------------------------
// Changes to this file must follow the http://aka.ms/api-review process.
// ------------------------------------------------------------------------------
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.Versioning.TargetFramework(".NETFramework,Version=v4.6.1", FrameworkDisplayName = ".NET Framework 4.6.1")]
[assembly: System.CLSCompliant(true)]
[assembly: System.Runtime.InteropServices.DefaultDllImportSearchPaths(System.Runtime.InteropServices.DllImportSearchPath.AssemblyDirectory | System.Runtime.InteropServices.DllImportSearchPath.System32)]
[assembly: System.Reflection.AssemblyDefaultAlias("System.Security.AccessControl")]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Reflection.AssemblyMetadata(".NETFrameworkAssembly", "")]
[assembly: System.Reflection.AssemblyMetadata("Serviceable", "True")]
[assembly: System.Reflection.AssemblyMetadata("PreferInbox", "True")]
[assembly: System.Reflection.AssemblyMetadata("IsTrimmable", "True")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyCopyright("© Microsoft Corporation. All rights reserved.")]
[assembly: System.Reflection.AssemblyDescription("Internal implementation package not meant for direct consumption. Please do not reference directly. \nProvides base classes that enable managing access and audit control lists on securable objects.\r\n\r\nCommonly Used Types:\r\nSystem.Security.AccessControl.AccessRule\r\nSystem.Security.AccessControl.AuditRule\r\nSystem.Security.AccessControl.ObjectAccessRule\r\nSystem.Security.AccessControl.ObjectAuditRule\r\nSystem.Security.AccessControl.ObjectSecurity")]
[assembly: System.Reflection.AssemblyFileVersion("6.0.21.52210")]
[assembly: System.Reflection.AssemblyInformationalVersion("6.0.0+4822e3c3aa77eb82b2fb33c9321f923cf11ddde6")]
[assembly: System.Reflection.AssemblyProduct("Microsoft® .NET")]
[assembly: System.Reflection.AssemblyTitle("System.Security.AccessControl")]
[assembly: System.Reflection.AssemblyMetadata("RepositoryUrl", "https://github.com/dotnet/runtime")]
[assembly: System.Reflection.AssemblyVersionAttribute("6.0.0.0")]
[assembly: System.Runtime.CompilerServices.ReferenceAssembly]
[assembly: System.Reflection.AssemblyFlagsAttribute((System.Reflection.AssemblyNameFlags)0x70)]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.AccessControlActions))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.AccessControlModification))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.AccessControlSections))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.AccessControlType))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.AccessRule))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.AccessRule<>))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.AceEnumerator))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.AceFlags))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.AceQualifier))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.AceType))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.AuditFlags))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.AuditRule))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.AuditRule<>))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.AuthorizationRule))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.AuthorizationRuleCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.CommonAce))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.CommonAcl))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.CommonObjectSecurity))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.CommonSecurityDescriptor))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.CompoundAce))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.CompoundAceType))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.ControlFlags))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.CustomAce))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.DiscretionaryAcl))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.GenericAce))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.GenericAcl))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.GenericSecurityDescriptor))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.InheritanceFlags))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.KnownAce))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.NativeObjectSecurity))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.ObjectAccessRule))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.ObjectAce))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.ObjectAceFlags))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.ObjectAuditRule))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.ObjectSecurity))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.ObjectSecurity<>))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.PrivilegeNotHeldException))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.PropagationFlags))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.QualifiedAce))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.RawAcl))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.RawSecurityDescriptor))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.ResourceType))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.SecurityInfos))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.AccessControl.SystemAcl))]
