name: Backport PR to branch
on:
  issue_comment:
    types: [created]
  schedule:
    # once a day at 13:00 UTC to cleanup old runs
    - cron: '0 13 * * *'

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write

jobs:
  backport:
    uses: dotnet/arcade/.github/workflows/backport-base.yml@4c3a4cf7d53de7fab8056c9307ac1422640cbdad # main
