// <auto-generated />
#pragma warning disable

#if !NET9_0_OR_GREATER

namespace System.Diagnostics.CodeAnalysis;

using Diagnostics;
using Diagnostics.CodeAnalysis;

/// <summary>
/// [AttributeUsage(AttributeTargets.Property, Inherited = false)]
/// </summary>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
[AttributeUsage(AttributeTargets.Property, Inherited = false)]
//Link: https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.featureswitchdefinitionattribute
#if PolyPublic
public
#endif
sealed class FeatureSwitchDefinitionAttribute : Attribute
{
    /// <summary>
    /// Initializes a new instance of the <see cref="FeatureSwitchDefinitionAttribute"/> class
    /// with the specified feature switch name.
    /// </summary>
    /// <param name="switchName">
    /// The name of the feature switch that provides the value for the specified property.
    /// </param>
    public FeatureSwitchDefinitionAttribute(string switchName)
    {
        SwitchName = switchName;
    }

    /// <summary>
    /// The name of the feature switch that provides the value for the specified property.
    /// </summary>
    public string SwitchName { get; }
}

#endif