// <auto-generated />
#pragma warning disable

#if PolyGuard

namespace Polyfills;

using System.Runtime.CompilerServices;
using System;
using System.Diagnostics.CodeAnalysis;

#if PolyPublic
public
#endif

static partial class Guard
{
    public static string NotNullOrWhiteSpace(
        [NotNull] string? value,
        [CallerArgumentExpression("value")] string argumentName = "")
    {
#if NET8_0_OR_GREATER
        ArgumentException.ThrowIfNullOrWhiteSpace(value, argumentName);
        return value;
#else
        if (value == null)
        {
            throw new ArgumentNullException(argumentName);
        }

        if (value.Length == 0)
        {
            throw new ArgumentException("Argument cannot be empty.", argumentName);
        }

        foreach (var ch in value)
        {
            if (!char.IsWhiteSpace(ch))
            {
                return value;
            }
        }

        throw new ArgumentException("Argument cannot be whitespace.", argumentName);
#endif
    }

#if FeatureMemory
    public static Memory<char> NotNullOrWhiteSpace(
        [NotNull] Memory<char>? value,
        [CallerArgumentExpression("value")] string argumentName = "")
    {
        if (value == null)
        {
            throw new ArgumentNullException(argumentName);
        }

        if (value.Value.Length == 0)
        {
            throw new ArgumentException("Argument cannot be empty.", argumentName);
        }

        foreach (var ch in value.Value.Span)
        {
            if (!char.IsWhiteSpace(ch))
            {
                return value.Value;
            }
        }

        throw new ArgumentException("Argument cannot be whitespace.", argumentName);
    }

    public static ReadOnlyMemory<char> NotNullOrWhiteSpace(
        [NotNull] ReadOnlyMemory<char>? value,
        [CallerArgumentExpression("value")] string argumentName = "")
    {
        if (value == null)
        {
            throw new ArgumentNullException(argumentName);
        }

        if (value.Value.Length == 0)
        {
            throw new ArgumentException("Argument cannot be empty.", argumentName);
        }

        foreach (var ch in value.Value.Span)
        {
            if (!char.IsWhiteSpace(ch))
            {
                return value.Value;
            }
        }

        throw new ArgumentException("Argument cannot be whitespace.", argumentName);
    }
#endif
}
#endif