// <auto-generated />
#pragma warning disable

namespace Polyfills;

static partial class Polyfill
{
    static void ThrowNoElementsException() =>
        throw new System.InvalidOperationException("Sequence contains no elements");
}
