// <auto-generated />

#pragma warning disable

#if FeatureMemory

using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace Polyfills;

using System;
using System.Text;

static partial class Polyfill
{
#if !NET9_0_OR_GREATER

    /// <summary>
    /// Determines whether the specified value appears at the start of the span.
    /// </summary>
    /// <param name="target">The span to search.</param>
    /// <param name="value">The value to compare.</param>
    //Link: https://learn.microsoft.com/en-us/dotnet/api/system.memoryextensions.endswith#system-memoryextensions-endswith-1(system-readonlyspan((-0))-0)
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool StartsWith<T>(this ReadOnlySpan<T> target, T value)
        where T : IEquatable<T>? =>
        target.Length != 0 && (target[0]?.Equals(value) ?? (object?)value is null);

#endif

#if NETFRAMEWORK || NETSTANDARD || NETCOREAPP2X

    /// <summary>
    /// Determines whether a read-only character span begins with a specified value when compared using a specified <see cref="StringComparison"/> value.
    /// </summary>
    /// <param name="target">The source span.</param>
    /// <param name="other">The sequence to compare to the beginning of the source span.</param>
    /// <param name="comparison">An enumeration value that determines how span and value are compared.</param>
    /// <returns><c>true</c> if value matches the beginning of span; otherwise, <c>false</c>.</returns>
    //Link: https://learn.microsoft.com/en-us/dotnet/api/system.memoryextensions.startswith#system-memoryextensions-startswith-1(system-readonlyspan((-0))-system-readonlyspan((-0)))
    public static bool StartsWith(
        this ReadOnlySpan<char> target,
        string other,
        StringComparison comparison = StringComparison.CurrentCulture) =>
        target.StartsWith(other.AsSpan(), comparison);

    /// <summary>
    /// Determines whether a specified sequence appears at the start of a span.
    /// </summary>
    /// <param name="target">The source span.</param>
    /// <param name="other">The sequence to compare to the beginning of the source span.</param>
    /// <returns><c>true</c> if value matches the beginning of span; otherwise, <c>false</c>.</returns>
    //Link: https://learn.microsoft.com/en-us/dotnet/api/system.memoryextensions.startswith#system-memoryextensions-startswith-1(system-span((-0))-system-readonlyspan((-0)))
    public static bool StartsWith(
        this Span<char> target,
        string other) =>
        target.StartsWith(other.AsSpan());

#endif

}

#endif
