<Project>

  <PropertyGroup>
    <SkipCurrentVersionOverrides Condition="'$(DotNetBuildFromVMR)' == 'true' or '$(DotNetBuildSourceOnly)' == 'true'">true</SkipCurrentVersionOverrides>
  </PropertyGroup>

  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />

  <PropertyGroup>
    <TargetFramework>$(BundledNETCoreAppTargetFramework)</TargetFramework>
    <IsMSBuildTaskProject>true</IsMSBuildTaskProject>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
    <EnableKnownPackVersionUpdatesForCurrentTargetFramework Condition="'$(DotNetBuildFromVMR)' == 'true' or '$(DotNetBuildSourceOnly)' == 'true'">false</EnableKnownPackVersionUpdatesForCurrentTargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(RepoRoot)src\Resolvers\Microsoft.NET.Sdk.WorkloadManifestReader\SdkFeatureBand.cs" LinkBase="Common"/>
    <Compile Include="$(RepoRoot)src\Common\WorkloadSetVersion.cs" LinkBase="Common" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Framework" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Deployment.DotNet.Releases" />
    <PackageReference Include="NuGet.Packaging" />
    <PackageReference Include="NuGet.Versioning" />
    <PackageReference Include="System.IO.Hashing" />
  </ItemGroup>

  <!-- Global usings -->
  <ItemGroup>
    <Using Include="Microsoft.Build.Framework" />
    <Using Include="Microsoft.Build.Utilities" />
     <!-- This causes conflicts with System.Threading.Tasks.Task. Giving it an alias to avoid the conflict. -->
    <Using Include="Microsoft.Build.Utilities.Task" Alias="Task" />
  </ItemGroup>

  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />

</Project>
