<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(BundledNETCoreAppTargetFramework)</TargetFramework>
    <IsMSBuildTaskProject>true</IsMSBuildTaskProject>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(RepoRoot)src\Resolvers\Microsoft.NET.Sdk.WorkloadManifestReader\SdkFeatureBand.cs" LinkBase="Common"/>
    <Compile Include="$(RepoRoot)src\Common\WorkloadSetVersion.cs" LinkBase="Common" />
    <Compile Include="$(RepoRoot)src\Resolvers\Microsoft.NET.Sdk.WorkloadManifestReader\WorkloadManifestReader*.cs" LinkBase="WorkloadManifestReader" />
    <Compile Include="$(RepoRoot)src\Resolvers\Microsoft.NET.Sdk.WorkloadManifestReader\WorkloadManifest.cs" LinkBase="WorkloadManifestReader" />
    <Compile Include="$(RepoRoot)src\Resolvers\Microsoft.NET.Sdk.WorkloadManifestReader\WorkloadManifestFormatException.cs" LinkBase="WorkloadManifestReader" />
    <Compile Include="$(RepoRoot)src\Resolvers\Microsoft.NET.Sdk.WorkloadManifestReader\WorkloadDefinition.cs" LinkBase="WorkloadManifestReader" />
    <Compile Include="$(RepoRoot)src\Resolvers\Microsoft.NET.Sdk.WorkloadManifestReader\WorkloadId.cs" LinkBase="WorkloadManifestReader" />
    <Compile Include="$(RepoRoot)src\Resolvers\Microsoft.NET.Sdk.WorkloadManifestReader\WorkloadPack.cs" LinkBase="WorkloadManifestReader" />
    <Compile Include="$(RepoRoot)src\Resolvers\Microsoft.NET.Sdk.WorkloadManifestReader\WorkloadPackId.cs" LinkBase="WorkloadManifestReader" />
    <Compile Include="$(RepoRoot)src\Resolvers\Microsoft.NET.Sdk.WorkloadManifestReader\WorkloadPackKind.cs" LinkBase="WorkloadManifestReader" />
    <Compile Include="$(RepoRoot)src\Resolvers\Microsoft.DotNet.MSBuildSdkResolver\FXVersion.cs" LinkBase="WorkloadManifestReader" />
    <EmbeddedResource Include="$(RepoRoot)src\Resolvers\Microsoft.NET.Sdk.WorkloadManifestReader\Strings.resx"
                      LinkBase="WorkloadManifestReader" GenerateSource="true" Namespace="Microsoft.NET.Sdk.Localization" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" />
    <PackageReference Include="Microsoft.Deployment.DotNet.Releases" />
    <PackageReference Include="NuGet.Packaging" />
    <PackageReference Include="NuGet.Versioning" />
    <PackageReference Include="System.IO.Hashing" />
  </ItemGroup>

  <!-- Global usings -->
  <ItemGroup>
    <Using Include="Microsoft.Build.Framework" />
    <Using Include="Microsoft.Build.Utilities" />
     <!-- This causes conflicts with System.Threading.Tasks.Task. Giving it an alias to avoid the conflict. -->
    <Using Include="Microsoft.Build.Utilities.Task" Alias="Task" />
  </ItemGroup>

</Project>
