// <auto-generated />
#pragma warning disable

#nullable enable

namespace Polyfills;
using System;
using System.Collections.Concurrent;
using System.Reflection;

/// <summary>
/// Static and thread safe wrapper around NullabilityInfoContext.
/// </summary>
#if PolyPublic
public
#endif
static partial class Polyfill
{
    static ConcurrentDictionary<ParameterInfo, NullabilityInfo> parameters = [];
    static ConcurrentDictionary<PropertyInfo, NullabilityInfo> properties = [];
    static ConcurrentDictionary<EventInfo, NullabilityInfo> events = [];
    static ConcurrentDictionary<FieldInfo, NullabilityInfo> fields = [];

    public static NullabilityInfo GetNullabilityInfo(this MemberInfo info)
    {
        if (info is PropertyInfo propertyInfo)
        {
            return propertyInfo.GetNullabilityInfo();
        }

        if (info is EventInfo eventInfo)
        {
            return eventInfo.GetNullabilityInfo();
        }

        if (info is FieldInfo fieldInfo)
        {
            return fieldInfo.GetNullabilityInfo();
        }

        throw new ArgumentException($"Unsupported type:{info.GetType().FullName}");
    }

    public static NullabilityState GetNullability(this MemberInfo info) =>
        GetReadOrWriteState(info.GetNullabilityInfo());

    public static bool IsNullable(this MemberInfo info)
    {
        var nullability = info.GetNullabilityInfo();
        return IsNullable(info.Name, nullability);
    }

    public static NullabilityInfo GetNullabilityInfo(this FieldInfo info) =>
        fields.GetOrAdd(
            info,
            static inner =>
            {
                var context = new NullabilityInfoContext();
                return context.Create(inner);
            });

    public static NullabilityState GetNullability(this FieldInfo info) =>
        GetReadOrWriteState(info.GetNullabilityInfo());

    public static bool IsNullable(this FieldInfo info)
    {
        var nullability = info.GetNullabilityInfo();
        return IsNullable(info.Name, nullability);
    }

    public static NullabilityInfo GetNullabilityInfo(this EventInfo info) =>
        events.GetOrAdd(
            info,
            static inner =>
            {
                var context = new NullabilityInfoContext();
                return context.Create(inner);
            });

    public static NullabilityState GetNullability(this EventInfo info) =>
        GetReadOrWriteState(info.GetNullabilityInfo());

    public static bool IsNullable(this EventInfo info)
    {
        var nullability = info.GetNullabilityInfo();
        return IsNullable(info.Name, nullability);
    }

    public static NullabilityInfo GetNullabilityInfo(this PropertyInfo info) =>
        properties.GetOrAdd(
            info,
            static inner =>
            {
                var context = new NullabilityInfoContext();
                return context.Create(inner);
            });

    public static NullabilityState GetNullability(this PropertyInfo info) =>
        GetReadOrWriteState(info.GetNullabilityInfo());

    public static bool IsNullable(this PropertyInfo info)
    {
        var nullability = info.GetNullabilityInfo();
        return IsNullable(info.Name, nullability);
    }

    public static NullabilityInfo GetNullabilityInfo(this ParameterInfo info) =>
        parameters.GetOrAdd(
            info,
            static inner =>
            {
                var context = new NullabilityInfoContext();
                return context.Create(inner);
            });

    public static NullabilityState GetNullability(this ParameterInfo info) =>
        GetReadOrWriteState(info.GetNullabilityInfo());

    public static bool IsNullable(this ParameterInfo info)
    {
        var nullability = info.GetNullabilityInfo();
        return IsNullable(info.Name!, nullability);
    }

    static NullabilityState GetReadOrWriteState(NullabilityInfo info)
    {
        if (info.ReadState == NullabilityState.Unknown)
        {
            return info.WriteState;
        }

        return info.ReadState;
    }

    static NullabilityState GetKnownState(string name, NullabilityInfo info)
    {
        var read = info.ReadState;
        if (read != NullabilityState.Unknown)
        {
            return read;
        }

        var write = info.WriteState;
        if (write != NullabilityState.Unknown)
        {
            return write;
        }

        throw new($"The nullability of '{info.Type.FullName}.{name}' is unknown. Assembly: {info.Type.Assembly.FullName}.");
    }

    static bool IsNullable(string name, NullabilityInfo info) =>
        GetKnownState(name, info) == NullabilityState.Nullable;
}