# No CI trigger rely on Pipeline trigger only
trigger: none

resources:
  pipelines:
    - pipeline: nugetclientofficial
      source: NuGet.Client-Official
      trigger:
        branches:
          - dev
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release

variables:
- group: NuGet.Client Build Variables

extends:
  template: azure-pipelines/MicroBuild.1ES.Unofficial.yml@MicroBuildTemplate
  parameters:
    sdl:
      sourceAnalysisPool: VSEngSS-MicroBuild2022-1ES
      binskim:
        enabled: true
        scanOutputDirectoryOnly: true
      policheck:
        enabled: true
      suppression:
        suppressionFile: $(Build.SourcesDirectory)\.gdn\.gdnsuppress
      tsa:
        enabled: true
        config:
          codebaseName: "NuGet.Client_Trusted_dev"
          instanceUrl: https://dev.azure.com/devdiv/
          projectName: DevDiv
          areaPath: "DevDiv\\NuGet\\NuGet Clients"
          notificationAliases: $(TsaNotificationAliases)
    pool:
      name: AzurePipelines-EO
      image: VSEngSS-MicroBuild2022-1ES
      os: windows
    stages:
    - stage: compliance
      displayName: "Run Compliance Tasks"
      jobs:
      - job: Static_Analysis
        displayName: "Static Analysis"
        timeoutInMinutes: 180
        pool:
          name: VSEngSS-MicroBuild2022-1ES
        templateContext:
          inputs:
            - input: pipelineArtifact
              pipeline: nugetclientofficial
              artifactName: symbols - NonRTM
              targetPath: $(Pipeline.Workspace)\symbols\NonRTM

        steps:
        - pwsh: "Get-ChildItem Env: | Sort-Object Name | Format-Table -Wrap -AutoSize"
          displayName: 'Print Environment Variables'

        - task: APIScan@2
          displayName: Run APIScan
          inputs:
            softwareFolder: $(Pipeline.Workspace)\symbols
            softwareName: "NuGet.Client"
            softwareVersionNum: "$(Resources.Pipeline.nugetclientofficial.RunName)"
            isLargeApp: false
            toolVersion: "Latest"
            azureSubscription: 'VSEng-APIScanSC'
            preserveLogsFolder: true
          env:
            AzureServicesAuthConnectionString: RunAs=App;AppId=d318cba7-db4d-4fb3-99e1-01879cb74e91;TenantId=72f988bf-86f1-41af-91ab-2d7cd011db47;ServiceConnectionId=93e24264-c5e6-4681-8175-ec8a41668480;
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)

        - pwsh: |
            $tsaOptionsPath = Join-Path $env:AGENT_TEMPDIRECTORY 'TSAOptions.json'
            Write-Host "TsaNotificationAliases: $env:TSA_NOTIFICATION_ALIASES"
            $notificationAliases = @($env:TSA_NOTIFICATION_ALIASES | ConvertFrom-Json)
            $tsaOptions = [ordered]@{
              tsaVersion = 'TsaV2'
              codebaseName = 'NuGet.Client_Trusted_dev'
              instanceUrl = 'https://dev.azure.com/devdiv/'
              projectName = 'DevDiv'
              areaPath = 'DevDiv\\NuGet\\NuGet Clients'
              notificationAliases = $notificationAliases
            }

            $json = $tsaOptions | ConvertTo-Json -Depth 5
            Write-Host $json
            Write-Host "Writing TSA options to $tsaOptionsPath"
            $json| Out-File -FilePath $tsaOptionsPath -Encoding utf8 -Force
          displayName: Write TSAOptions.json
          env:
            TSA_NOTIFICATION_ALIASES: $(TsaNotificationAliases)

        - task: TSAUpload@2
          displayName: TSA upload
          inputs:
            GdnPublishTsaOnboard: True
            GdnPublishTsaConfigFile: $(Agent.TempDirectory)\TSAOptions.json
