# This is a pipeline that will run NuGet.Client's Visual Studio daily integration tests

pr: none
trigger:
  branches:
    include:
    - dev

parameters:
- name: ApexAgentCleanup
  displayName: Cleanup VS Apex test machine
  type: string
  default: Always
  values:
    - Always
    - Never
    - OnSuccess

resources:
  pipelines:
  - pipeline: DartLab
    source: DartLab
    branch: main
  repositories:
  - repository: DartLabTemplates
    type: git
    name: DartLab.Templates
    ref: refs/heads/main

variables:
  DOTNET_NOLOGO: 1
  CI: true
  Codeql.Enabled: false
  SourceBranch: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]

stages:
- stage: Build
  displayName: Build NuGet and tests
  jobs:
  - job: Build
    timeoutInMinutes: 170
    pool:
      name: VSEngSS-MicroBuild2022-1ES
    steps:
    - template: vs-test/build.yml

# Dartlab's template defines this in its own stage
- template: vs-test/apex.yml
  parameters:
    condition: "and(succeeded(), ne(variables['RunApexTests'], 'false'))"
    dependsOn:
    - Build
    variables:
    - name: bootstrapperUrl
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.bootstrapperUrl']]
    - name: RunSettingsDrop
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.RunSettingsDrop']]
    - name: VsBootstrapperBranch
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.VsBootstrapperBranch']]
    bootstrapperUrl: $(bootstrapperUrl)
    runSettingsURI: https://vsdrop.corp.microsoft.com/file/v1/$(RunSettingsDrop);NuGet.Tests.Apex.Daily.runsettings
    testExecutionJobTimeoutInMinutes: 380 # cloud test minimum
    testDeploymentCleanupMode: ${{parameters.ApexAgentCleanup}}
    VsBootstrapperBranch: $(VsBootstrapperBranch)
