# This is a pipeline that will run NuGet.Client's Visual Studio integration tests

pr: none
trigger:
  branches:
    include:
    - dev-*

parameters:
# Specific tests
- name: RunApexTests
  displayName: Run Apex tests
  type: boolean
  default: true
- name: RunEndToEndTests
  displayName: Run end-to-end tests
  type: boolean
  default: true

# Dartlab options
- name: DartLabEnvironment
  displayName: DartLab Environment
  type: string
  default: Production
  values:
  - Production
  - Staging
- name: E2EPart1AgentCleanup
  displayName: Delete or keep E2E Part 1 machine for debugging
  type: string
  default: delete
  values:
  - delete
  - stop
- name: E2EPart2AgentCleanup
  displayName: Delete or keep E2E Part 2 machine for debugging
  type: string
  default: delete
  values:
  - delete
  - stop
- name: ApexAgentCleanup
  displayName: Cleanup VS Apex test machine
  type: string
  default: Always
  values:
    - Always
    - Never
    - OnSuccess

resources:
  pipelines:
  - pipeline: DartLab
    source: DartLab
    branch: main
  repositories:
  - repository: DartLabTemplates
    type: git
    name: DartLab.Templates
    ref: refs/heads/main

variables:
  DOTNET_NOLOGO: 1
  CI: true
  Codeql.Enabled: false
  SourceBranch: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]

stages:
- stage: Build
  displayName: Build NuGet and tests
  jobs:
  - job: Build
    timeoutInMinutes: 170
    pool:
      name: VSEngSS-MicroBuild2022-1ES
    steps:
    - template: vs-test/build.yml

# Dartlab's template defines this in its own stage
- template: vs-test/end_to_end.yml
  parameters:
    stageName: VS_EndToEnd_Part1
    stageDisplayName: Part 1
    condition: "and(succeeded(), ne(variables['RunEndToEndTests'], 'false'))"
    dependsOn:
    - Build
    variables:
    - name: VsBootstrapperUrl
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.bootstrapperUrl']]
    - name: VsBaseBuildDrop
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.BaseBuildDrop']]
    - name: QBuildSessionId
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.QBuildSessionId']]
    - name: RunSettingsDrop
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.RunSettingsDrop']]
    baseBuildDrop: $(VsBaseBuildDrop)
    bootstrapperUrl: $(VsBootstrapperUrl)
    DartLabEnvironment: ${{parameters.DartLabEnvironment}}
    part: "InstallPackageTest.ps1,UninstallPackageTest.ps1,UpdatePackageTest.ps1"
    QBuildSessionId: $(QBuildSessionId)
    runSettingsURI: https://vsdrop.corp.microsoft.com/file/v1/$(RunSettingsDrop);NuGet.Tests.Apex.runsettings
    testExecutionJobTimeoutInMinutes: 100
    testMachineCleanUpStrategy: ${{parameters.E2EPart1AgentCleanup}}

# Dartlab's template defines this in its own stage
- template: vs-test/end_to_end.yml
  parameters:
    stageName: VS_EndToEnd_Part2
    stageDisplayName: Part 2
    condition: "and(succeeded(), ne(variables['RunEndToEndTests'], 'false'))"
    dependsOn:
    - Build
    variables:
    - name: VsBootstrapperUrl
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.bootstrapperUrl']]
    - name: VsBaseBuildDrop
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.BaseBuildDrop']]
    - name: QBuildSessionId
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.QBuildSessionId']]
    - name: RunSettingsDrop
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.RunSettingsDrop']]
    baseBuildDrop: $(VsBaseBuildDrop)
    bootstrapperUrl: $(VsBootstrapperUrl)
    DartLabEnvironment: ${{parameters.DartLabEnvironment}}
    part: "BuildIntegratedTest.ps1,ExecuteInitScriptTest.ps1,FindPackageTest.ps1,GetPackageTest.ps1,GetProjectTest.ps1,LegacyPackageRefProjectTest.ps1,NativeProjectTest.ps1,NetCoreProjectTest.ps1,PackTest.ps1,ProjectRetargeting.ps1,ServicesTest.ps1,Settings.ps1,SyncPackageTest.ps1,TabExpansionTest.ps1,UniversalWindowsProjectTest.ps1"
    QBuildSessionId: $(QBuildSessionId)
    runSettingsURI: https://vsdrop.corp.microsoft.com/file/v1/$(RunSettingsDrop);NuGet.Tests.Apex.runsettings
    testExecutionJobTimeoutInMinutes: 100
    testMachineCleanUpStrategy: ${{parameters.E2EPart2AgentCleanup}}

# Dartlab's template defines this in its own stage
- template: vs-test/apex.yml
  parameters:
    condition: "and(succeeded(), ne(variables['RunApexTests'], 'false'))"
    dependsOn:
    - Build
    variables:
    - name: bootstrapperUrl
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.bootstrapperUrl']]
    - name: RunSettingsDrop
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.RunSettingsDrop']]
    - name: VsBootstrapperBranch
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.VsBootstrapperBranch']]
    bootstrapperUrl: $(bootstrapperUrl)
    runSettingsURI: https://vsdrop.corp.microsoft.com/file/v1/$(RunSettingsDrop);NuGet.Tests.Apex.runsettings
    testExecutionJobTimeoutInMinutes: 380 # cloud test minimum
    testDeploymentCleanupMode: ${{parameters.ApexAgentCleanup}}
    VsBootstrapperBranch: $(VsBootstrapperBranch)
