parameters:

- name: pool_Linux
  type: object

- name: pool_LinuxArm64
  type: object

# Scope of jobs which are executed
- name: scope
  type: string
  values:
  # run only windows jobs
  - scout
  # run several legs e.g. stage1/stage2 for basic testing
  - lite
  # run everything
  - full
  # run source build outer loop (Mono jobs)
  - source-build-outer-loop

- name: useMicrosoftBuildAssetsForTests
  type: boolean
  default: true

# True when build is running from dotnet/dotnet directly
- name: isBuiltFromVmr
  type: boolean
  default: true

# True when the build is a build run from the production pipeline
- name: isOfficialBuild
  type: boolean
  default: false

- name: desiredSigning
  type: string
  default: ''

- name: desiredFinalVersionKind
  type: string
  default: ''

# List of verifications to run during PRs.
- name: verifications
  type: object
  default: []

# Indicates whether runtime dependent jobs are excluded.
- name: excludeRuntimeDependentJobs
  type: boolean
  default: false

stages:
- ${{ if or(in(parameters.scope, 'full') , contains(join(';', parameters.verifications), 'source-build-')) }}:
  - template: source-build-and-validate.yml
    parameters:
      pool_Linux: ${{ parameters.pool_Linux }}
      pool_LinuxArm64: ${{ parameters.pool_LinuxArm64 }}
      useMicrosoftBuildAssetsForTests: ${{ parameters.useMicrosoftBuildAssetsForTests }}
      isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
      isOfficialBuild: ${{ parameters.isOfficialBuild }}
      desiredSigning: ${{ parameters.desiredSigning }}
      desiredFinalVersionKind: ${{ parameters.desiredFinalVersionKind }}
      excludeRuntimeDependentJobs: ${{ parameters.excludeRuntimeDependentJobs }}
      
      # Description of the source build legs to run.
      # This is described here as a parameter to allow two separate stages to be produced from this list (one for building
      # and one for validation). Because this template is not directly within a pipeline, stage, or job, we can't reference
      # variables as template expressions. So we can't do things like '${{ format('{0}_Online_MsftSdk', variables.centOSStreamName) }}'.
      # The variable value will be empty in that case. Instead, each leg defines a distro name that source-build-and-validate.yml uses
      # to determine which variable to use for determining the various parameter values which are based on variables.
      #
      # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
      # Changing the `disableSigning` parameter requires adding or removing the build name and source-built artifact
      # patterns in the ../steps/vmr-validate-signing.yml file.
      legs:

        ### Source-build verification legs ###

        - ${{ if in(parameters.scope, 'source-build-outer-loop') }}:

          - buildNameFormat: 'SB_{0}_Mono_Offline_MsftSdk'
            distro: centos
            targetArchitecture: x64
            buildFromArchive: true             # ✅
            enablePoison: false                # 🚫
            runOnline: false                   # 🚫
            useMonoRuntime: true               # ✅
            useSystemLibraries: false          # 🚫
            withPreviousSDK: false             # 🚫
            disableSigning: true               # ✅
            createSourceArtifact: false        # 🚫
            extraProperties: /p:DotNetSkipTestsRequiringMicrosoftArtifacts=true

          - buildNameFormat: 'SB_{0}_Mono_Offline_CurrentSourceBuiltSdk'
            distro: centos
            targetArchitecture: x64
            buildFromArchive: true             # ✅
            enablePoison: false                # 🚫
            runOnline: false                   # 🚫
            useMonoRuntime: true               # ✅
            useSystemLibraries: false          # 🚫
            withPreviousSDK: false             # 🚫
            disableSigning: true               # ✅
            createSourceArtifact: false        # 🚫
            reuseBuildArtifactsFrom: 'SB_{0}_Mono_Offline_MsftSdk_x64'
            extraProperties: /p:DotNetSkipTestsRequiringMicrosoftArtifacts=true

        - ${{ else }}:

          # Stage 1 leg is built in full scope, or lite when any of the `source-build-` verifications are requested.
          - buildNameFormat: 'SB_{0}_Online_MsftSdk'
            distro: centos
            targetArchitecture: x64
            buildFromArchive: false            # 🚫
            enablePoison: false                # 🚫
            runOnline: true                    # ✅
            useMonoRuntime: false              # 🚫
            useSystemLibraries: false          # 🚫
            withPreviousSDK: false             # 🚫
            disableSigning: true               # ✅
            createSourceArtifact: false        # 🚫
            ${{ if in(parameters.scope, 'lite') }}:
              extraProperties: /p:DotNetSkipTestsRequiringMicrosoftArtifacts=true

          - ${{ if containsValue(parameters.verifications, 'source-build-stage2') }}:

            - buildNameFormat: 'SB_{0}_Offline_CurrentSourceBuiltSdk'
              distro: centos
              targetArchitecture: x64
              buildFromArchive: false            # 🚫
              enablePoison: false                # 🚫
              runOnline: false                   # 🚫
              useMonoRuntime: false              # 🚫
              useSystemLibraries: false          # 🚫
              withPreviousSDK: false             # 🚫
              disableSigning: true               # ✅
              createSourceArtifact: false        # 🚫
              reuseBuildArtifactsFrom: 'SB_{0}_Online_MsftSdk_x64'
              ${{ if in(parameters.scope, 'lite') }}:
                extraProperties: /p:DotNetSkipTestsRequiringMicrosoftArtifacts=true

          ### Additional legs for full build ###
          - ${{ if in(parameters.scope, 'full') }}:

            - buildNameFormat: 'SB_{0}_Offline_MsftSdk'
              distro: ubuntu
              targetArchitecture: x64
              buildFromArchive: false            # 🚫
              enablePoison: false                # 🚫
              excludeOmniSharpTests: false       # 🚫
              runOnline: false                   # 🚫
              useMonoRuntime: false              # 🚫
              useSystemLibraries: false          # 🚫
              withPreviousSDK: false             # 🚫
              disableSigning: true               # ✅
              createSourceArtifact: false        # 🚫

            - buildNameFormat: 'SB_{0}_Offline_PreviousSourceBuiltSdk'
              distro: centos
              targetArchitecture: x64
              buildFromArchive: false            # 🚫
              enablePoison: true                 # ✅
              runOnline: false                   # 🚫
              useMonoRuntime: false              # 🚫
              useSystemLibraries: false          # 🚫
              withPreviousSDK: true              # ✅
              disableSigning: true               # ✅
              createSourceArtifact: false        # 🚫

            - buildNameFormat: 'SB_{0}_Offline_MsftSdk'
              distro: almalinux
              targetArchitecture: x64
              buildFromArchive: false            # 🚫
              enablePoison: false                # 🚫
              runOnline: false                   # 🚫
              useMonoRuntime: false              # 🚫
              useSystemLibraries: false          # 🚫
              withPreviousSDK: false             # 🚫
              disableSigning: true               # ✅
              createSourceArtifact: false        # 🚫

            - buildNameFormat: 'SB_{0}_Offline_MsftSdk'
              distro: alpine
              targetArchitecture: x64
              buildFromArchive: false            # 🚫
              enablePoison: false                # 🚫
              runOnline: false                   # 🚫
              useMonoRuntime: false              # 🚫
              useSystemLibraries: false          # 🚫
              withPreviousSDK: false             # 🚫
              disableSigning: true               # ✅
              createSourceArtifact: false        # 🚫

            - buildNameFormat: 'SB_{0}_Offline_MsftSdk'
              distro: centos
              targetArchitecture: x64
              buildFromArchive: false            # 🚫
              enablePoison: false                # 🚫
              runOnline: false                   # 🚫
              useMonoRuntime: false              # 🚫
              useSystemLibraries: false          # 🚫
              withPreviousSDK: false             # 🚫
              disableSigning: false              # 🚫
              createSourceArtifact: true         # ✅

            - buildNameFormat: 'SB_{0}_Online_PreviousSourceBuiltSdk'
              distro: centos
              targetArchitecture: x64
              buildFromArchive: false            # 🚫
              enablePoison: false                # 🚫
              runOnline: true                    # ✅
              useMonoRuntime: false              # 🚫
              useSystemLibraries: false          # 🚫
              withPreviousSDK: true              # ✅
              disableSigning: true               # ✅
              createSourceArtifact: false        # 🚫

            - buildNameFormat: 'SB_{0}_Offline_MsftSdk'
              distro: fedora
              targetArchitecture: x64
              buildFromArchive: true             # ✅
              enablePoison: false                # 🚫
              runOnline: false                   # 🚫
              useMonoRuntime: false              # 🚫
              useSystemLibraries: true           # ✅
              withPreviousSDK: false             # 🚫
              disableSigning: true               # ✅
              createSourceArtifact: false        # 🚫

            - buildNameFormat: 'SB_{0}Arm64_Offline_MsftSdk'
              distro: ubuntu
              targetArchitecture: arm64
              buildFromArchive: false            # 🚫
              enablePoison: false                # 🚫
              runOnline: false                   # 🚫
              useMonoRuntime: false              # 🚫
              useSystemLibraries: false          # 🚫
              withPreviousSDK: false             # 🚫
              disableSigning: true               # ✅
              createSourceArtifact: false        # 🚫

            - buildNameFormat: 'SB_{0}_Offline_CurrentSourceBuiltSdk'
              distro: fedora
              targetArchitecture: x64
              buildFromArchive: false            # 🚫
              enablePoison: false                # 🚫
              runOnline: false                   # 🚫
              useMonoRuntime: false              # 🚫
              useSystemLibraries: false          # 🚫
              withPreviousSDK: false             # 🚫
              disableSigning: true               # ✅
              createSourceArtifact: false        # 🚫
              reuseBuildArtifactsFrom: 'SB_{0}_Offline_MsftSdk_x64'
