parameters:
- name: dotnetDotnetRunId
  displayName: 'Specific dotnet-dotnet run ID number (e.g `2108850`)'
  type: string
  default: ' '

stages:
- stage: stage
  variables:
  - template: /eng/pipelines/templates/variables/vmr-build.yml@self
  # GH access token for SB bot - BotAccount-dotnet-sb-bot-pat
  - group: Dotnet-SourceBuild-Secrets
  jobs:
  - template: /eng/pipelines/templates/jobs/sdk-diff-tests.yml@self
    parameters:
      sbJobName: ${{ format('SB_{0}_Offline_MsftSdk', variables.centOSStreamName) }}
      msftJobName: Linux
      sbTargetRid: ${{ variables.centOSStreamX64Rid }}
      msftTargetRid: ${{ variables.linuxX64Rid }}
      architecture: x64
      dotnetDotnetRunId: ${{ parameters.dotnetDotnetRunId }}
      publishTestResultsPr: true

  - template: /eng/pipelines/templates/jobs/sdk-diff-tests.yml@self
    parameters:
      sbJobName: ${{ format('SB_{0}_Offline_MsftSdk', variables.almaLinuxName) }}
      msftJobName: Linux
      sbTargetRid: ${{ variables.almaLinuxX64Rid }}
      msftTargetRid: ${{ variables.linuxX64Rid }}
      architecture: x64
      dotnetDotnetRunId: ${{ parameters.dotnetDotnetRunId }}

  - template: /eng/pipelines/templates/jobs/sdk-diff-tests.yml@self
    parameters:
      sbJobName: ${{ format('SB_{0}_Offline_MsftSdk', variables.alpineName) }}
      msftJobName: Linux_Alpine
      sbTargetRid: ${{ variables.alpineX64Rid }}
      msftTargetRid: ${{ variables.linuxMuslX64Rid }}
      architecture: x64
      dotnetDotnetRunId: ${{ parameters.dotnetDotnetRunId }}

  - template: /eng/pipelines/templates/jobs/sdk-diff-tests.yml@self
    parameters:
      sbJobName: ${{ format('SB_{0}_Offline_MsftSdk', variables.fedoraName) }}
      msftJobName: Linux
      sbTargetRid: ${{ variables.fedoraX64Rid }}
      msftTargetRid: ${{ variables.linuxX64Rid }}
      architecture: x64
      dotnetDotnetRunId: ${{ parameters.dotnetDotnetRunId }}

  - template: /eng/pipelines/templates/jobs/sdk-diff-tests.yml@self
    parameters:
      sbJobName: ${{ format('SB_{0}_Offline_MsftSdk', variables.ubuntuName) }}
      msftJobName: Linux
      sbTargetRid: ${{ variables.ubuntuX64Rid }}
      msftTargetRid: ${{ variables.linuxX64Rid }}
      architecture: x64
      dotnetDotnetRunId: ${{ parameters.dotnetDotnetRunId }}

  - template: /eng/pipelines/templates/jobs/sdk-diff-tests.yml@self
    parameters:
      sbJobName: ${{ format('SB_{0}Arm64_Offline_MsftSdk', variables.ubuntuName) }}
      msftJobName: Linux
      sbTargetRid: ${{ variables.ubuntuArm64Rid }}
      msftTargetRid: ${{ variables.linuxArm64Rid }}
      architecture: arm64
      dotnetDotnetRunId: ${{ parameters.dotnetDotnetRunId }}
