stages:
- stage: VMR_Scan
  displayName: VMR Scan
  dependsOn: []
  jobs:
  - job: Scan
    displayName: Scan
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - script: |
        source ./eng/common/tools.sh
        InitializeDotNetCli true
        dotnet='./.dotnet/dotnet'
        "$dotnet" tool restore
      displayName: Initialize tooling

    - script: |
        set -x
        PATH=$PATH:$(Build.SourcesDirectory)/.dotnet
        export DOTNET_ROOT="$(pwd)/.dotnet"
        ./.dotnet/dotnet darc vmr scan --vmr "$(Build.SourcesDirectory)" --tmp "$(Agent.TempDirectory)"
        darc vmr scan --vmr "$(Build.SourcesDirectory)" --tmp "$(Agent.TempDirectory)"
      displayName: Scan binaries
