stages:
- stage: Scan
  dependsOn: []
  jobs:
  - job: Scan
    pool:
      name: $(DncEngInternalBuildPool)
      image: 1es-ubuntu-2204
      os: linux

    steps:
    - checkout: self

    - script: |
        source ./eng/common/tools.sh
        InitializeDotNetCli true
        echo "##vso[task.setvariable variable=DotNetPath]$_InitializeDotNetCli"
      displayName: Install .NET CLI
  
    - script: |
        $(DotNetPath)/dotnet tool restore
      displayName: Restore tools

    - script: >
        $(DotNetPath)/dotnet darc vmr scan-cloaked-files
        --vmr "$(Build.SourcesDirectory)"
        --tmp "$(Agent.TempDirectory)"
        || (echo '##[error]Found cloaked files in the VMR' && exit 1)
      displayName: Scan for cloaked files
      continueOnError: true