### This stage builds https://github.com/dotnet/dotnet with varying parameters
### If run in a PR, new changes are applied to a local copy of the VMR, then it is built and tested

parameters:
- name: desiredSigning
  type: string
  default: ''

- name: desiredIbc
  type: string
  default: ''

- name: desiredFinalVersionKind
  type: string
  default: ''

# Scope of jobs which are executed
- name: scope
  type: string
  values:
  # run only windows jobs
  - scout
  # run several legs e.g. stage1/stage2 for basic testing
  - lite
  # run everything
  - full

# True when build is running from dotnet/dotnet directly
- name: isBuiltFromVmr
  type: boolean
  default: true

# True when the build is a build run from the production pipeline
- name: isOfficialBuild
  type: boolean
  default: false

# List of verifications to run during PRs.
- name: verifications
  type: object
  default: []

# These are not expected to be passed it but rather just object variables reused below
- name: pool_Linux
  type: object
  default:
    name: $(defaultPoolName)
    image: $(poolImage_Linux)
    demands: ImageOverride -equals $(poolImage_Linux)
    os: linux

- name: pool_Windows
  type: object
  default:
    name: $(defaultPoolName)
    image: $(poolImage_Windows)
    demands: ImageOverride -equals $(poolImage_Windows)
    os: windows

- name: pool_LinuxArm64
  type: object
  default:
    name: $(poolName_LinuxArm64)
    image: $(poolImage_LinuxArm64)
    demands: ImageOverride -equals $(poolImage_LinuxArm64)
    hostArchitecture: Arm64
    os: linux

- name: pool_Mac
  type: object
  default:
    name: Azure Pipelines
    vmImage: $(poolImage_Mac)
    os: macOS


- name: pool_Linux_Shortstack
  type: object
  default:
    name: $(shortStackPoolName)
    image: $(poolImage_Linux)
    demands: ImageOverride -equals $(poolImage_Linux)
    os: linux

# Indicates whether to exclude runtime dependent jobs.
# This is used to skip building the cross-OS DACs and other runtime dependent jobs in non-1xx branches.
- name: excludeRuntimeDependentJobs
  type: boolean
  default: false

stages:

#### VERTICAL BUILD (Official) ####
- stage: VMR_Vertical_Build
  displayName: VMR Vertical Build
  dependsOn: []
  variables:
  - template: ../variables/vmr-build.yml
    parameters:
      desiredSigning: ${{ parameters.desiredSigning }}
      isOfficialBuild: ${{ parameters.isOfficialBuild }}
      desiredIBC: ${{ parameters.desiredIBC }}
      desiredFinalVersionKind: ${{ parameters.desiredFinalVersionKind }}
  jobs:
  - template: ../jobs/vmr-build.yml
    parameters:
      buildName: OSX
      isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
      sign: true
      signType: dryrun
      pool: ${{ parameters.pool_Mac }}
      targetOS: osx
      targetArchitecture: x64

