### This stage builds https://github.com/dotnet/dotnet with varying parameters
### If run in a PR, new changes are applied to a local copy of the VMR, then it is built and tested

parameters:
- name: desiredSigning
  type: string
  default: ''

- name: desiredIbc
  type: string
  default: ''

# Scope of jobs which are executed
- name: scope
  type: string
  values:
  # run several legs e.g. win/linux/mac for basic testing
  - lite
  # run everything
  - full

# True when build is running from dotnet/dotnet directly
- name: isBuiltFromVmr
  type: boolean
  default: true

# List of verifications to run during PRs.
- name: verifications
  type: object
  default: []

# These are not expected to be passed it but rather just object variables reused below
- name: pool_Linux
  type: object
  default:
    name: $(defaultPoolName)
    image: $(poolImage_Linux)
    demands: ImageOverride -equals $(poolImage_Linux)
    os: linux

- name: pool_Windows
  type: object
  default:
    name: $(defaultPoolName)
    image: $(poolImage_Windows)
    demands: ImageOverride -equals $(poolImage_Windows)
    os: windows

- name: pool_LinuxArm64
  type: object
  default:
    name: $(poolName_LinuxArm64)
    image: $(poolImage_LinuxArm64)
    demands: ImageOverride -equals $(poolImage_LinuxArm64)
    hostArchitecture: Arm64
    os: linux

- name: pool_Mac
  type: object
  default:
    name: Azure Pipelines
    vmImage: $(poolImage_Mac)
    os: macOS


- name: pool_Linux_Shortstack
  type: object
  default:
    name: $(shortStackPoolName)
    image: $(poolImage_Linux)
    demands: ImageOverride -equals $(poolImage_Linux)
    os: linux

stages:

#### VERTICAL BUILD (Official) ####
- ${{ if or(in(parameters.scope, 'full') , contains(join(';', parameters.verifications), 'unified-build-')) }}:
  - stage: VMR_Vertical_Build
    displayName: VMR Vertical Build
    dependsOn: []
    variables:
    - template: ../variables/vmr-build.yml
      parameters:
        desiredSigning: ${{ parameters.desiredSigning }}
        desiredIBC: ${{ parameters.desiredIBC }}
    jobs:

      - template: ../jobs/vmr-build.yml
        parameters:
          buildName: Android_Shortstack_1
          isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
          sign: ${{ variables.signEnabled }}
          pool: ${{ parameters.pool_Linux_Shortstack }}
          container:
            name: ${{ variables.androidCrossContainerName }}
            image: ${{ variables.androidCrossContainerImage }}
          targetOS: android
          targetArchitecture: arm64

      - template: ../jobs/vmr-build.yml
        parameters:
          buildName: Android_Shortstack_2
          isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
          sign: ${{ variables.signEnabled }}
          pool: ${{ parameters.pool_Linux_Shortstack }}
          container:
            name: ${{ variables.androidCrossContainerName }}
            image: ${{ variables.androidCrossContainerImage }}
          targetOS: android
          targetArchitecture: arm64

      - template: ../jobs/vmr-build.yml
        parameters:
          buildName: Android_Shortstack_
          isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
          sign: ${{ variables.signEnabled }}
          pool: ${{ parameters.pool_Linux_Shortstack }}
          container:
            name: ${{ variables.androidCrossContainerName }}
            image: ${{ variables.androidCrossContainerImage }}
          targetOS: android
          targetArchitecture: arm64

      - template: ../jobs/vmr-build.yml
        parameters:
          buildName: Android_Shortstack_3
          isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
          sign: ${{ variables.signEnabled }}
          pool: ${{ parameters.pool_Linux_Shortstack }}
          container:
            name: ${{ variables.androidCrossContainerName }}
            image: ${{ variables.androidCrossContainerImage }}
          targetOS: android
          targetArchitecture: arm64

      - template: ../jobs/vmr-build.yml
        parameters:
          buildName: Android_Shortstack_4
          isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
          sign: ${{ variables.signEnabled }}
          pool: ${{ parameters.pool_Linux_Shortstack }}
          container:
            name: ${{ variables.androidCrossContainerName }}
            image: ${{ variables.androidCrossContainerImage }}
          targetOS: android
          targetArchitecture: arm64

      - template: ../jobs/vmr-build.yml
        parameters:
          buildName: Android_Shortstack_5
          isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
          sign: ${{ variables.signEnabled }}
          pool: ${{ parameters.pool_Linux_Shortstack }}
          container:
            name: ${{ variables.androidCrossContainerName }}
            image: ${{ variables.androidCrossContainerImage }}
          targetOS: android
          targetArchitecture: arm64

      - template: ../jobs/vmr-build.yml
        parameters:
          buildName: Android_Shortstack_6
          isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
          sign: ${{ variables.signEnabled }}
          pool: ${{ parameters.pool_Linux_Shortstack }}
          container:
            name: ${{ variables.androidCrossContainerName }}
            image: ${{ variables.androidCrossContainerImage }}
          targetOS: android
          targetArchitecture: arm64

      - template: ../jobs/vmr-build.yml
        parameters:
          buildName: Android_Shortstack_7
          isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
          sign: ${{ variables.signEnabled }}
          pool: ${{ parameters.pool_Linux_Shortstack }}
          container:
            name: ${{ variables.androidCrossContainerName }}
            image: ${{ variables.androidCrossContainerImage }}
          targetOS: android
          targetArchitecture: arm64

      - template: ../jobs/vmr-build.yml
        parameters:
          buildName: Android_Shortstack_8
          isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
          sign: ${{ variables.signEnabled }}
          pool: ${{ parameters.pool_Linux_Shortstack }}
          container:
            name: ${{ variables.androidCrossContainerName }}
            image: ${{ variables.androidCrossContainerImage }}
          targetOS: android
          targetArchitecture: arm64

      - template: ../jobs/vmr-build.yml
        parameters:
          buildName: Android_Shortstack_9
          isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
          sign: ${{ variables.signEnabled }}
          pool: ${{ parameters.pool_Linux_Shortstack }}
          container:
            name: ${{ variables.androidCrossContainerName }}
            image: ${{ variables.androidCrossContainerImage }}
          targetOS: android
          targetArchitecture: arm64

      - template: ../jobs/vmr-build.yml
        parameters:
          buildName: Android_Shortstack_10
          isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
          sign: ${{ variables.signEnabled }}
          pool: ${{ parameters.pool_Linux_Shortstack }}
          container:
            name: ${{ variables.androidCrossContainerName }}
            image: ${{ variables.androidCrossContainerImage }}
          targetOS: android
          targetArchitecture: arm64

