### This stage builds https://github.com/dotnet/dotnet with varying parameters
### If run in a PR, new changes are applied to a local copy of the VMR, then it is built and tested

parameters:
- name: desiredSigning
  type: string
  default: ''

- name: desiredIbc
  type: string
  default: ''

- name: desiredFinalVersionKind
  type: string
  default: ''

# Scope of jobs which are executed
- name: scope
  type: string
  values:
  # run only windows jobs
  - scout
  # run several legs e.g. stage1/stage2 for basic testing
  - lite
  # run everything
  - full

# True when build is running from dotnet/dotnet directly
- name: isBuiltFromVmr
  type: boolean
  default: true

- name: isOfficialBuild
  type: boolean
  default: false

# List of verifications to run during PRs.
- name: verifications
  type: object
  default:
  - source-build-stage1
  - source-build-stage2
  - unified-build-android-arm64
  - unified-build-browser-wasm
  - unified-build-iossimulator-arm64
  - unified-build-linux-buildtests
  - unified-build-windows-buildtests
  - unified-build-windows-x64
  - unified-build-windows-x86

# These are not expected to be passed it but rather just object variables reused below
- name: pool_Linux
  type: object
  default:
    name: $(defaultPoolName)
    image: $(poolImage_Linux)
    demands: ImageOverride -equals $(poolImage_Linux)
    os: linux

- name: pool_Windows
  type: object
  default:
    name: $(defaultPoolName)
    image: $(poolImage_Windows)
    demands: ImageOverride -equals $(poolImage_Windows)
    os: windows

- name: pool_LinuxArm64
  type: object
  default:
    name: $(poolName_LinuxArm64)
    image: $(poolImage_LinuxArm64)
    demands: ImageOverride -equals $(poolImage_LinuxArm64)
    hostArchitecture: Arm64
    os: linux

- name: pool_Mac
  type: object
  default:
    name: Azure Pipelines
    vmImage: $(poolImage_Mac)
    os: macOS


- name: pool_Linux_Shortstack
  type: object
  default:
    name: $(shortStackPoolName)
    image: $(poolImage_Linux)
    demands: ImageOverride -equals $(poolImage_Linux)
    os: linux

- name: featureBand
  displayName: 'Target Feature Band'
  type: string
  default: 'Detect by Branch Name'
  values:
    - 'Detect by Branch Name'
    - '1xx'
    - '>= 2xx'

stages:
- template: vmr-verticals.yml
  parameters:
    desiredSigning: ${{ parameters.desiredSigning }}
    isOfficialBuild: ${{ parameters.isOfficialBuild }}
    desiredIbc: ${{ parameters.desiredIbc }}
    desiredFinalVersionKind: ${{ parameters.desiredFinalVersionKind }}
    isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
    scope: ${{ parameters.scope }}
    verifications: ${{ parameters.verifications }}
    # Exclude runtime dependent jobs for any branch not producing a 1xx version since runtime-related repos aren't built in that context
    # Will exclude runtime-dependent jobs when either of the following are true:
    #   - 'Detect By Branch Name' was selected for the feature band: branch is not main and does not contain '.1xx' but does end with 'xx'.
    #   - '>= 2xx' was selected for the feature band
    ${{ if or(and(eq(parameters.featureBand, 'Detect by Branch Name'), ne(variables['Build.SourceBranch'], 'refs/heads/main'), not(contains(variables['Build.SourceBranch'], '.1xx')), endsWith(variables['Build.SourceBranch'], 'xx')), eq(parameters.featureBand, '>= 2xx')) }}:
      excludeRuntimeDependentJobs: true

- ${{ if and(parameters.isBuiltFromVmr, eq(parameters.isOfficialBuild, true)) }}:
  - stage: Publish_Build_Assets
    displayName: Publish Assets
    dependsOn:
    - VMR_Vertical_Build
    - VMR_SourceOnly_Build
    jobs:
    - template: /eng/common/templates-official/job/publish-build-assets.yml
      parameters:
        publishUsingPipelines: true
        publishAssetsImmediately: true
        enablePublishBuildArtifacts: true
        pool: ${{ parameters.pool_Linux }}
        symbolPublishingAdditionalParameters: '/p:PublishSpecialClrFiles=true'
        publishingVersion: 4
        assetManifestsPattern: |
          **/manifests/**/*.xml
          !*Sdk_*_Artifacts/**/VerticalManifest.xml

  - template: vmr-validation.yml
    parameters:
      desiredSigning: ${{ parameters.desiredSigning }}
      isOfficialBuild: ${{ parameters.isOfficialBuild }}

- ${{ if notin(parameters.scope, 'scout') }}:
  - template: source-build-stages.yml
    parameters:
      pool_Linux: ${{ parameters.pool_Linux }}
      pool_LinuxArm64: ${{ parameters.pool_LinuxArm64 }}
      scope: ${{ parameters.scope }}
      isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
      desiredFinalVersionKind: ${{ parameters.desiredFinalVersionKind }}
      verifications: ${{ parameters.verifications }}
      ${{ if ne(parameters.scope, 'full') }}:
        # For PR/lite builds, we don't rely on Microsoft build assets for testing because not all of the required assets
        # are available from the subset of jobs that get build in PRs compared to the full build. Instead, we run
        # the tests in the same job as the build and filter out some of the tests that can't be executed in this state.
        useMicrosoftBuildAssetsForTests: false
