parameters:
- name: name
  type: string

- name: type
  type: string

- name: command
  type: string

stages:
- stage: VMR_Scan_${{ parameters.type }}
  displayName: Scan ${{ parameters.name }}
  dependsOn: []
  jobs:
  - job: Scan
    displayName: Scan ${{ parameters.name }}
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - script: |
        source ./eng/common/tools.sh
        InitializeDotNetCli true
        dotnet='./.dotnet/dotnet'
        "$dotnet" tool restore
      displayName: Initialize tooling
      workingDirectory: $(Build.SourcesDirectory)/src/installer

    - script: |
        set -x
        PATH=$PATH:$(Build.SourcesDirectory)/.dotnet
        export DOTNET_ROOT="$(pwd)/.dotnet"
        ./.dotnet/dotnet darc vmr ${{ parameters.command }} --vmr "$(Build.SourcesDirectory)" --tmp "$(Agent.TempDirectory)"
        darc vmr scan --vmr "$(Build.SourcesDirectory)" --tmp "$(Agent.TempDirectory)"
      displayName: Scan ${{ parameters.name }}
      workingDirectory: $(Build.SourcesDirectory)/src/installer
